### ISSUE TITLE
rp promise bind not working?

### ISSUE THREAD

**Issue by maorhayoun** [request/request-promise#102]
I might be missing something, but the obvious example simply doesn't work as I expect

`
rp('http://google.com').promise().bind({a:1}).then(() => { console.log(this) });
`

will return "this" as empty object.

thanks

**Comment by analog-nico** [comment]
Hi @maorhayoun there is actually a [test](https://github.com/request/request-promise/blob/master/test/spec/request-test.js#L729-L739) that makes sure this works.

Did you try this?

``` js
rp('http://google.com').promise().bind({a:1})
    .then(function () {
        console.log(this.a)
    });
```

**Comment by maorhayoun** [comment]
well, it seems that using the arrow function affects the bound this object.
your example works, mine returns empty.

**Comment by analog-nico** [comment]
I see. Probably the latest version of Bluebird already fixed it. Unfortunately, Request-Promise is still using an old version. I'll look into it.

**Comment by analog-nico** [comment]
I am currently working on updating Request-Promise with the latest Bluebird version and found out that your code is still not working.

``` js
var rp = require('request-promise');
var BPromise = require('bluebird');

rp('http://google.com').promise().bind({a:1}).then(() => { console.log(this); }); // ==> {}
BPromise.resolve().bind({a:1}).then(() => { console.log(this); }); // ==> {}
BPromise.resolve().bind({a:1}).then(function () { console.log(this); }); // ==> { a: 1 }
```

This means either that there is a misconception about using the new ES6 function type (I can't tell. I didn't use ES6 yet.) or that Bluebird doesn't support it yet. In any way you should ask the Bluebird community.

**Comment by highdali** [comment]
do i can't use arrow function ?!

**Comment by analog-nico** [comment]
Hi @highdali , it works like shown in my last comment. If you paste your code snippet here I can probably say more.

**Comment by highdali** [comment]
```
requestP(URL)
.then(body => {
  const $ = cheerio.load(body);
  const bookid = $('#page_body > form:nth-child(6) > ul > li > dl > dt > a').attr('href').split('=')[1];
  return bookid;
})
.catch(error => console.error(error));
```

TypeError: Cannot read property 'then' of undefined

**Comment by highdali** [comment]
Oh! I got it.

**Comment by analog-nico** [comment]
@highdali Fixed? Perfect.

As your question was not related to this issue please open a new issue next time or even better use Gitter. I'll get notified there as well. Happy coding!
