### ISSUE TITLE
How to post form data via request-promise

### ISSUE THREAD

**Issue by allaboutapis** [request/request-promise#105]
I have the following API POST that I am doing through request module:

var https = require('https');
var fs = require('fs');
var request = require('request');

var filename = '/Users/***/Desktop/FilesFiles/Responses-Original.csv';
 var text = fs.readFileSync(filename,'utf-8');

var url =/url here/;

var req = 

request.post(url, function (err, resp, body) {
	  if (err) {
	    console.log('Error!');
	  } else {
	    console.log('URL: ' + body);
	  }
 });
 var form = req.form();
 form.append('FileContents', fs.createReadStream(filename));

How can I make the same call through request-promise module?

**Comment by analog-nico** [comment]
Try this:

``` js
var rp = require('request-promise');

/* ... */

var req = rp.post(url)
    .then(function (body) {
        console.log('URL: ' + body);
    })
    .catch(function (err) {
        console.log('Error!');
    });

var form = req.form();
form.append('FileContents', fs.createReadStream(filename));
```

**Comment by analog-nico** [comment]
Sorry, I had to update the comment above a few times.

**Comment by allaboutapis** [comment]
req.form() is not a function!! :(

**Comment by allaboutapis** [comment]
This worked. Sorry, I was trying the old comment. Thank u so sooo much!!! :)

**Comment by analog-nico** [comment]
Did you try the latest version of the code above? An earlier version - the one you got per email - was wrong. If you tried the latest version, I'll test it myself...

**Comment by analog-nico** [comment]
Alright. You are welcome!

**Comment by allaboutapis** [comment]
I have one more doubt. How do I chain the same using .then now?

**Comment by analog-nico** [comment]
Sorry, I don't understand...

My code snippet is using `.then(...)`. Or what do you want to chain?

**Comment by analog-nico** [comment]
I see, you opened https://github.com/request/request-promise/issues/106 for that.

**Comment by allaboutapis** [comment]
I want to call the above function and then do a .then(). 

That is giving me this error - Cannot read property then of undefined.

**Comment by allaboutapis** [comment]
I found the solution - returning req works. Sorry for the trouble. And thanks for the timely response.

**Comment by analog-nico** [comment]
Ok. Happy coding!

**Comment by michgboxy2** [comment]
option : function option(method, uri, sign){

	return {
	method : method,
	uri : uri,
	headers : {		
		'User-Agent': 'Request-Promise',
		'Accept' : 'application/json',
		'Content-Type' : 'application/json',
		'Authorization' : authcode,
		'Signature' : sign,
		'Timestamp' : strtime,
		"Nonce" : nonce,
		"SignatureMethod" : sha,
		"TerminalID" : terminalId
	},

	json : true
}

}





       var uri = 
      'https://sandbox.interswitchng.com/api/v2/quickteller/payments/advices';
     var options = keys.option("POST",uri,keys.signed(uri));



    options.form = {
    paymentCode : req.body.paymentCode,
    customerId : req.body.customerId,
    customerMobile : req.body.customerMobile,
    customerEmail : req.body.email,
    amount : req.body.amount,
    requestReference : "2438"+num
   }

i'm having a content-type not supportted error... any help?

**Comment by analog-nico** [comment]
@michgboxy2 Using the `form` option has big effects on the request. In particular, it will chance your `Content-Type` header. It looks to me that you just want to send JSON to a REST API. Thus check out the respective [expample in the cheat sheet](https://github.com/request/request-promise#post-data-to-a-json-rest-api).

**Comment by michgboxy2** [comment]
what i'm trying to do is send a user form input to a REST API.. does the form option disrupt my already set headers? .  because the body option doesn't look like it can take values from the request.body.
