### ISSUE TITLE
Using .then on API POST in request-promise

### ISSUE THREAD

**Issue by allaboutapis** [request/request-promise#106]
var rp = require('request-promise');

/* ... */

var req = rp.post(url);

var form = req.form();
form.append('FileContents', fs.createReadStream(filename));

req.then(function (body) {
        console.log('URL: ' + body);
    })
    .catch(function (err) {
        console.log('Error!');
    });

This works but I am not able to use a .then on the Response. How do I do the same?

**Comment by analog-nico** [comment]
What do you mean by ".then on the Response"?

I suggest you study how to use promises in general. `rp.post(url)` returns a promise. What you do with it is common promise handling.

**Comment by analog-nico** [comment]
I guess I can close this one after you said in https://github.com/request/request-promise/issues/105 that you found a solution.
