### ISSUE TITLE
POST json not stringified

### ISSUE THREAD

**Issue by cyberwombat** [request/request-promise#110]
According to docs:

    json: true // Automatically stringifies the body to JSON

However that is not the case for me (3.0.0 and earlier). I need to manually call `json.stringify` on my body object **and** set `json: true`. Failure to do both causes body to be sent unencoded.

I did my testing by accessing the iContact API and using mock to dump out the requests where I can see when it fails and can see if the body is escaped or not.

**Comment by analog-nico** [comment]
Weird. This is my test code and it works as expected:

``` js
var express = require('express');
var bodyParser = require('body-parser');

var app = express();
app.use(bodyParser.json());

app.post('/json', function (req, res) {
    res.json({ more: req.body.some });
});

var server = app.listen(3333, function () {

    var rp = require('request-promise');

    var options = {
        method: 'POST',
        uri: 'http://localhost:3333/json',
        body: {
            some: 'payload'
        },
        json: true // Automatically stringifies the body to JSON
    };

    rp(options)
        .then(function (parsedBody) {
            console.dir(parsedBody.more);
        })
        .catch(function (err) {
            console.error(err);
        })
        .finally(function () {
            server.close();
        });

});
```

**Comment by cyberwombat** [comment]
Hmm. I was using `nock` to dumo the requests and now i wonder if my errors were not related and that nock somehow parses my json making me think it was not stringified. Not being able to see the server requests its hard to debug so lemme close that and go have a beer.

**Comment by analog-nico** [comment]
Enjoy your beer! 🍻
