### ISSUE TITLE
Bearer Token

### ISSUE THREAD

**Issue by chrishawn** [request/request-promise#111]
what is the syntax for doing an authorization bearer token?

what i was doing in request doesn't seem to work.

**Comment by analog-nico** [comment]
Please have a look at the [Request documentation](https://github.com/request/request#http-authentication). Request-Promise works the same.

Let me know if that helped.

**Comment by chrishawn** [comment]
ok i think it was a capitalization issue, got it working with

```
     var options = {
                url: APIURL,
                headers: {
                    'User-Agent': 'client'
                },
                auth: {
                    'bearer': accessToken
                }
            };
```

**Comment by analog-nico** [comment]
Great!
