### ISSUE TITLE
Moving forward: Please create these repos for me

### ISSUE THREAD

**Issue by analog-nico** [request/request-promise#112]
Hi @simov I have no rights to create new repositories in the request org but I need them to move forward with the demanded support of other promise implementations (#65, #71).

- Repo: **promise-core**, to be published to npm as **@request/promise-core**. Will be the core logic already designed in a way that it can be easily migrated to `request@next` in the future. After I did the test migration yesterday I now know how to do the design. :)
- Repo: **request-promise-native**, to be published as **request-promise-native**. Readily configured `promise-core` for native promises.
- Repo: **request-promise-any**, to be published as **request-promise-any**. Readily configured `promise-core` for the use with `any-promise`.
- Repo: **request-promise-bluebird**, to be published as **request-promise-bluebird**. Readily configured `promise-core` for `bluebird` promises. At least in the beginning identical to `request-promise`.

In particular, the `request-promise-xyz` packages will allow me to not introduce breaking changes into `request-promise` and to make the installation process (single `npm install` only) as easy as possible for the user.

If you are ok with making the request org a bit more crowded just create empty repos for me. Or feel free to mention other maintainers to join the decision making. Thanks!

**Comment by simov** [comment]
Sure, I'm going to add around 30 modules on my own pretty soon. I don't see a problem in having lots of repositories - if they are documented and maintained, even better.

So you need the following repositories:
- promise-core
- request-promise-native
- request-promise-any
- request-promise-bluebird
?

I'm going to add them to the Promise team with Admin permissions which means that you'll be able to add external collaborators to them. Also I will promote you as a Team Maintainer of the Promises team. Basically this gives you permissions to add more members to the team from the request org pool.

Lastly you need only @request/promise-core published on NPM by me, correct? I'll give you publish rights after that.

**Comment by analog-nico** [comment]
Yes, exactly, those 4. Thanks!

I will let you know later, once `promise-core` is ready to get published for the first time. I'll prepare everything so that you'll only have to clone it, hit `npm publish`, and give me publish rights.

Btw, after I published all those packages the next item on my laundry list is our joint documentation webpage.

**Comment by simov** [comment]
Done!

BTW I published a dummy package.json for @request/promise-core as version 0.0.0. You should be added as owner there though NPM is being funky ATM and is throwing me some errors.

**Comment by analog-nico** [comment]
I checked everything. All clear. Thanks!
