### ISSUE TITLE
How to define timeout.

### ISSUE THREAD

**Issue by bluethefish** [request/request-promise#116]
How do I define timeout request?

**Comment by analog-nico** [comment]
Have a look at [Request's options](https://github.com/request/request#requestoptions-callback). There is a `timeout` option.

**Comment by analog-nico** [comment]
Did it help @bluethefish ? Can I close this issue or can I help you with the solution?

**Comment by bluethefish** [comment]
k all good.

**Comment by analog-nico** [comment]
Alright, have a nice day.

**Comment by viktornordling** [comment]
@bluethefish I think the word you were looking for was "thanks".

**Comment by KeynesYouDigIt** [comment]
Whats the default set to? or is there none?

**Comment by shaahiiin** [comment]
@KeynesYouDigIt
It is mentioned in the request options section in the doc.
https://github.com/request/request#requestoptions-callback

    Note that if the underlying TCP connection cannot be established,
    the OS-wide TCP connection timeout will overrule the `timeout` option (the
    default in Linux can be anywhere from 20-120 seconds).

You may also want to read this section on timeouts:
https://github.com/request/request#timeouts

**Comment by pgraham** [comment]
@shaahiiin The docs only mention the default for connection timeouts. Does anyone know if there is a default read timeout?

**Comment by MumiaIrrequieta** [comment]
The documentation says there are "connection timeouts and read timeouts".
Is there a way to set each of them separately?

I'm having a connection timeout sometimes due to an unidentified network issue, and I would like to timeout as fast as I can to be able to retry the request without having to wait for the full timeout that is considering the time to receive the answer.
Thanks.

**Comment by analog-nico** [comment]
@MumiaIrrequieta For the connection timeout the docs also say:
```Note that increasing the timeout beyond the OS-wide TCP connection timeout will not have any effect```

Maybe you can use this to your advantage by reducing the timeout on the OS level.

**Comment by MumiaIrrequieta** [comment]
@analog-nico Thanks but I've been looking into it and the closest I found was "TCP_USER_TIMEOUT" but I'm uncertain if there is any nodeJs property that sets this. There is a socket timeout property, but I'm not sure it does what I want. I need to set the timeout for the first ACK I receive from the server, and stop counting there, not timing out while I'm waiting for the payload. Event at SO level there is not much documentation on how to enable "TCP_USER_TIMEOUT".

**Comment by analog-nico** [comment]
@MumiaIrrequieta Try asking the people over at the `request` library. They will know more about it. If you search through their issues I bet you may even find it answered already.

**Comment by MumiaIrrequieta** [comment]
OMG, so sorry. I got to this thread by a google search and didn't realize it's for "request-promise" and not "request".
Very sorry @analog-nico and thanks for the help.

**Comment by analog-nico** [comment]
No problem at all @MumiaIrrequieta . Cheers!

**Comment by Kumaraditya03** [comment]
Is there any default value for request-promise?? if yes, how much is it??
