### ISSUE TITLE
Dependence to Request

### ISSUE THREAD

**Issue by mathieug** [request/request-promise#117]
request-promise should list request as a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/)

[supertest-as-promised](https://github.com/WhoopInc/supertest-as-promised#node) is a good example for peer dependency usage.

**Comment by analog-nico** [comment]
This suggestion also came up in #76. I was thinking about this for a while. IMHO `request-promise` is not a plugin. Instead it is an extended version of `request`. However, debatable arguments aside people who use `request-promise` most likely don't use `request` separately. And for those people I would like to keep the installation process as easy as possible. `npm install request-promise --save`

Anyway, this should only be a conversation starter. Please give me more of your thoughts!

**Comment by mathieug** [comment]
Peer dependency is the only reasonable way to control the version of request. I don't like to use shrinkwrap with npm@3.

**Comment by analog-nico** [comment]
I just released `request-promise@4.0.0` which defines `request` as a peer dependency.
