### ISSUE TITLE
Handling network errors

### ISSUE THREAD

**Issue by tejasmanohar** [request/request-promise#120]
How should we handle network errors like ECONNRESET via request-promise? It appears as if this library has wrapped all errors to RequestError and thus, removed fields often used for failure identification like `.code`

**Comment by analog-nico** [comment]
Have a look at the [definition of the RequestError](https://github.com/request/request-promise/blob/master/lib/errors.js#L4-L19). the `.cause` is the `Error` you already know from using Request with a callback.

Also, the general error handling is documented [here](https://github.com/request/request-promise#rejected-promises-and-the-simple-option).

Does this answer you question?

**Comment by tejasmanohar** [comment]
ohhh awesome, gotcha. thanks!

**Comment by analog-nico** [comment]
You are welcome. :)

**Comment by tejasmanohar** [comment]
Hm, does `resolveWithFullResponse` apply to `.response` of a `StatusCodeError`? Not too clear to me by the docs.

**Comment by analog-nico** [comment]
`resolveWithFullResponse` only applies to successful responses. Only the `simple` option influences how the error handling works.

If you don't like the `false` default use:
``` js
var rp = require('request-promise').defaults({ resolveWithFullResponse: true });
```
