### ISSUE TITLE
How to specify relative paths?

### ISSUE THREAD

**Issue by peacechen** [request/request-promise#124]
Passing a relative path to request-promise doesn't work.  The code:

```
import reqPromise from "request-promise";

reqPromise("data/data.json")
	.then(...)

```
Returns the error

> RequestError: Error: Invalid URI "data/data.json"

Is there a good way to use relative paths?

**Comment by analog-nico** [comment]
Have a look at the [Request options](https://github.com/request/request#requestoptions-callback) and check out the `baseUrl` parameter.

**Comment by peacechen** [comment]
Let's say I've deployed the same app in 2 places:
http://myserver.com
http://otherserver.com

The data files are located at:
http://myserver.com/data/data.json
http://otherserver.com/data/data.json

respectively.  I want to avoid hard coding the base URL to either myserver.com or otherserver.com because the app should pull from the same server it's deployed on.  baseUrl doesn't help with that from my understanding and experimentally.  Am I misunderstanding how that should be used?

**Comment by analog-nico** [comment]
Well, you have a tools at hand. It now boils down to how you design your own system. I see the following alternatives how you could approach this:

- Use environment variables to set the `baseUrl`.
- You may use `http://localhost:<port>` as the `baseUrl`. Your hoster most likely already provides an environment variable for the port. At least all 4 hosters I used until now did so.
- However, the best alternative is to get rid of the request altogether. Modularise your api functions in a way that you can also call them internally by just a function call. The api endpoint you expose will only be a wrapper around the internal function. Thus you can either do an internal function call or your clients can still do the api call.

**Comment by peacechen** [comment]
Thanks for the tips.  It makes sense that this library doesn't try to determine the baseUrl, especially since it can be used on the back end as well as the front end.  Determining the baseUrl in those environments is vastly different.
