### ISSUE TITLE
request-promise doesn't follow redirects

### ISSUE THREAD

**Issue by colthreepv** [request/request-promise#127]
Seems to me that `request-promise` only follow redirects in `simple: true` mode.
It may be just a bug of the new v3.

Setting `{  simple: false, resolveWithFullResponse: true }` makes the request not go into a catch block, but resolves as a 302... not following the request.

I also tried putting `followRedirect: true` in the options object, but it doesn't change anything

I hope it's filed as a bug, because I had to fallback to simple `Promise.promisify(request)` at the moment, following multiple redirects it's a PITA, manually.

**Comment by colthreepv** [comment]
This is an extensive underlying library problem :sob:, sorry for doubting you ^_^

**Comment by analog-nico** [comment]
Oh, too bad.

As a workaround you may use the `transform` option:

``` js
var rp = require('request-promise');

function redirectOn302(body, response, resolveWithFullResponse) {
    if (response.statusCode === 302) {
        // Set the new url (this is the options object)
        this.url = response.['the redirect url somehow'];
        return rp(options);
    } else {
        return resolveWithFullResponse ? response : body;
    }
}

var options = {
    url: 'http://domain.com/will-redirect/',
    transform: redirectOn302
};

rp(options)
    .then(function (response) {
        // called after all redirects where followed
    });
```

I didn't test the code. But if I didn't miss something you may just need to implement `redirectOn302` once and use it in all your requests.

**Comment by graingert** [comment]
I can't seem to stop request-promise from following redirects now.

**Comment by analog-nico** [comment]
@graingert Did you set the options `followRedirect` to `false` and made sure that `followAllRedirects` is either not set or set to `false`?

**Comment by graingert** [comment]
Ah, sorry I it works for me now
