### ISSUE TITLE
str.replace is not a function

### ISSUE THREAD

**Issue by RichardJECooke** [request/request-promise#134]
Using this code:

```typescript
 const options = {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' },
                json: true,
                uri: this.config.peachPaymentsUrl + `v1/checkouts`,
                body: {
                    'authentication': {
                        'userId': this.config.peachPaymentsUsername,
                        'password': this.config.peachPaymentsPassword,
                        'entityId': this.config.peachPaymentsAdhocPaymentChannelId
                    },
                    'amount': mathHelper.getCentsAsRandsString(cents),
                    'currency': 'ZAR',
                    'description': 'Ekaya VIP',
                    'paymentType': 'DB' } //debit
            };

const response = await request(options);
```

Gives the error `str.replace is not a function`. If I remove the `headers` line the error goes away.

You can see what is happening in the depths of the request-promise code: 
![untitled](https://cloud.githubusercontent.com/assets/5468805/16617635/15222c00-4385-11e6-8caf-a665e617f635.png)

**Comment by analog-nico** [comment]
Since you post form data try to use the `form` option like in [this example](https://github.com/request/request-promise#post-like-html-forms-do) instead of `body` and drop the `'Content-Type'` header because it is added automatically then. Does this work?

**Comment by RichardJECooke** [comment]
Thanks, that works. But the problem is not that I'm using the API incorrectly, but rather when I do it gives me no error other than : 'str.replace is not a function' with no stack trace and no advice on what to fix. This bug is that the error isn't handled properly and a message given to the user.  That inner function shouldn't be trying to call `replace` on something that isn't a string.

**Comment by analog-nico** [comment]
True. However, this is an error produced by the underlying Request library which is reported here: https://github.com/request/request/issues/1463

My interpretation of the discussion on that issue is that the issue will be gone once the next major version of Request is released. (There is a major refactoring / modularization in the works. Request-Promise will be updated accordingly, of course.)

**Comment by simonron** [comment]
I have recentl upgraded to everything current at 16-2-2018... and I have just started getting this error on code that worked correctly before the update. Any ideas ?

**Comment by mgh128** [comment]
I encountered a similar error recently.  Do check whether the variable that .replace is operating on is actually a string, not an object.  If it's an object, use JSON.stringify() to convert it into a string serialisation first, then apply .replace, then convert back using JSON.parse()

**Comment by MyvizhiV** [comment]
> Since you post form data try to use the `form` option like in [this example](https://github.com/request/request-promise#post-like-html-forms-do) instead of `body` and drop the `'Content-Type'` header because it is added automatically then. Does this work?

@analog-nico it works well, Thank You

**Comment by andrey-tikhov** [comment]
Arrrgh. Investigated the [example](https://github.com/request/request-promise#post-like-html-forms-do) however request-debug shows that content-type header is added as 'content-type': 'application/json', not the "content-type": "application/x-www-form-urlencoded" which makes me really mad.
