### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by RobHarrisAZ** [request/request-promise#139]
Getting this warning consistently when calling two APIs.. The warning pops up on the second request call when the promise is resolved.  This was happening in 3.x as well and I was hoping 4.x would resolve it but it hasn't.
Here's the code causing this, it looks like things are being called correctly to me:
    var login = function() {
        var deferred = q.defer();

        request(options)
            .then(function (response) {
                var authCookie;
                var jar = request.jar();
                var sessionOptions = extend({}, options);
                
                if (response.statusCode === 200) {
                    authCookie = cookieParser.parse(response.headers['set-cookie'], 'LWSSO_COOKIE_KEY');
                    sessionOptions.uri = config.qcParams[config.tier].baseUrl + 'rest/site-session';
                    jar.setCookie(authCookie, sessionOptions.uri);
                    sessionOptions.jar = jar;
                    sessionOptions.method = 'POST';
                    request(sessionOptions)
                        .then(function (sessionResponse) {
                            var authFound = false,
                                cookies = sessionResponse.headers['set-cookie'].slice();
                            
                            if (sessionResponse.statusCode === 201) {
                                cookies.forEach(function (item) {
                                    if (item.indexOf('LWSSO_COOKIE_KEY') !== -1) {
                                        authFound = true;
                                    }
                                });
                        
                                if (!authFound) {
                                    cookies.push(authCookie);
                                }
                        
                                deferred.resolve(cookies);
                            }
                        })
                        .catch(function (err) {
                            console.log(err);
                            deferred.reject(err);
                        });
                } else {
                    deferred.reject(response.statusCode);
                }
            })
            .catch(function (err) {
                console.log(err);
                deferred.reject(err);
            });
        return deferred.promise;
    };

Here's the stack trace if that is helpful...
        at Request.module.exports.plumbing.init (d:\_Projects\QCNotifications\internal-api\node_modules\@request\promise-core\lib\plumbing.js:30:28)
        at Request.RP$initInterceptor [as init] (d:\_Projects\QCNotifications\internal-api\node_modules\@request\promise-core\configure\request2.js:40:27)
        at new Request (d:\_Projects\QCNotifications\internal-api\node_modules\request\request.js:129:8)
        at request (d:\_Projects\QCNotifications\internal-api\node_modules\request\index.js:55:10)
        at d:\_Projects\QCNotifications\internal-api\defects\qcLoginController.js:35:21
        at processImmediate [as _immediateCallback] (timers.js:383:17)
    From previous event:

**Comment by analog-nico** [comment]
Sorry, I can't reproduce it. Could you provide a code snippet that I can run in an independent script with `node snippet.js`?

However, I can give you some thoughts already. Since you chose the same title I assume you already read through #119 . In particular, please read https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

Most likely, the warning is not caused by `request-promise` but by the way you work with the promises. My guess is the line `request(sessionOptions)`. `request-promise` actually creates a promise there and that takes place within the `.then(function (response) { ... })` of the first request. Literally what the warning says.

The warning also says: "but was not returned from it". So add a `return`:

``` diff
var login = function() {
    var deferred = q.defer();

    request(options)
        .then(function (response) {
            var authCookie;
            var jar = request.jar();
            var sessionOptions = extend({}, options);

            if (response.statusCode === 200) {
                authCookie = cookieParser.parse(response.headers['set-cookie'], 'LWSSO_COOKIE_KEY');
                sessionOptions.uri = config.qcParams[config.tier].baseUrl + 'rest/site-session';
                jar.setCookie(authCookie, sessionOptions.uri);
                sessionOptions.jar = jar;
                sessionOptions.method = 'POST';
-               request(sessionOptions)
+               return request(sessionOptions)
                    .then(function (sessionResponse) {
                        var authFound = false,
                        cookies = sessionResponse.headers['set-cookie'].slice();

                        if (sessionResponse.statusCode === 201) {
                            cookies.forEach(function (item) {
                                if (item.indexOf('LWSSO_COOKIE_KEY') !== -1) {
                                    authFound = true;
                                }
                            });

                            if (!authFound) {
                                cookies.push(authCookie);
                            }

                            deferred.resolve(cookies);
                        }
-                   })
+                   });
                    // You don't need this anymore because of the return any error will go to the parent catch
-                   .catch(function (err) {
-                       console.log(err);
-                       deferred.reject(err);
-                   });
            } else {
                deferred.reject(response.statusCode);
            }
        })
        .catch(function (err) {
            console.log(err);
            deferred.reject(err);
        });
    return deferred.promise;
};
```

This probably will fix the warning but since we are already into refactoring your code let me suggest some more. Since you are working with multiple promises you should embrace their ability to assimilate each other:

``` diff
var login = function() {
    var deferred = q.defer();

    request(options)
        .then(function (response) {
            var authCookie;
            var jar = request.jar();
            var sessionOptions = extend({}, options);

+           if (response.statusCode !== 200) {
+               throw response.statusCode; // Will be forwarded to the catch below
+           }

-           if (response.statusCode === 200) {
            authCookie = cookieParser.parse(response.headers['set-cookie'], 'LWSSO_COOKIE_KEY');
            sessionOptions.uri = config.qcParams[config.tier].baseUrl + 'rest/site-session';
            jar.setCookie(authCookie, sessionOptions.uri);
            sessionOptions.jar = jar;
            sessionOptions.method = 'POST';
            return request(sessionOptions)
                // Since the promise is returned it is assimilated by the parent promise and you can move the .then(...) one level up
-                   .then(function (sessionResponse) {
-                       var authFound = false,
-                       cookies = sessionResponse.headers['set-cookie'].slice();
-
-                       if (sessionResponse.statusCode === 201) {
-                           cookies.forEach(function (item) {
-                               if (item.indexOf('LWSSO_COOKIE_KEY') !== -1) {
-                                   authFound = true;
-                               }
-                           });
-
-                           if (!authFound) {
-                               cookies.push(authCookie);
-                           }
-
-                           deferred.resolve(cookies);
-                       }
-                   });
            // Already handled above
-           } else {
-               deferred.reject(response.statusCode);
-           }
        })
+       .then(function (sessionResponse) {
+           var authFound = false,
+           cookies = sessionResponse.headers['set-cookie'].slice();
+
+           if (sessionResponse.statusCode === 201) {
+               cookies.forEach(function (item) {
+                   if (item.indexOf('LWSSO_COOKIE_KEY') !== -1) {
+                       authFound = true;
+                   }
+               });
+
+               if (!authFound) {
+                   cookies.push(authCookie);
+               }
+
+               deferred.resolve(cookies);
+           }
+       })
        .catch(function (err) {
            console.log(err);
            deferred.reject(err);
        });
    return deferred.promise;
};
```

BTW you have a bug:

``` diff
var login = function() {
    var deferred = q.defer();

    request(options)
        .then(function (response) {
            var authCookie;
            var jar = request.jar();
            var sessionOptions = extend({}, options);

            if (response.statusCode !== 200) {
                throw response.statusCode; // Will be forwarded to the catch below
            }

            authCookie = cookieParser.parse(response.headers['set-cookie'], 'LWSSO_COOKIE_KEY');
            sessionOptions.uri = config.qcParams[config.tier].baseUrl + 'rest/site-session';
            jar.setCookie(authCookie, sessionOptions.uri);
            sessionOptions.jar = jar;
            sessionOptions.method = 'POST';
            return request(sessionOptions)
        })
        .then(function (sessionResponse) {
            var authFound = false,
            cookies = sessionResponse.headers['set-cookie'].slice();

            if (sessionResponse.statusCode === 201) {
                cookies.forEach(function (item) {
                    if (item.indexOf('LWSSO_COOKIE_KEY') !== -1) {
                        authFound = true;
                    }
                });
 
                if (!authFound) {
                    cookies.push(authCookie);
                }
 
                deferred.resolve(cookies);
-           }
+           } else {
+               throw response.statusCode; // Or whatever you want to do in this case
+           }
        })
        .catch(function (err) {
            console.log(err);
            deferred.reject(err);
        });
    return deferred.promise;
};
```

And finally, you may improve how to use Q. There is the new library [`request-promise-any`](https://github.com/request/request-promise-any) now that is equivalent to `request-promise` but allows you to use any other promise library.

``` diff
+require('any-promise/register/q')
+var request = require('request-promise-any');


var login = function() {
-   var deferred = q.defer();

-   request(options)
+   return request(options)
        .then(function (response) {
            var authCookie;
            var jar = request.jar();
            var sessionOptions = extend({}, options);

            if (response.statusCode !== 200) {
                throw response.statusCode; // Will be forwarded to the catch below
            }

            authCookie = cookieParser.parse(response.headers['set-cookie'], 'LWSSO_COOKIE_KEY');
            sessionOptions.uri = config.qcParams[config.tier].baseUrl + 'rest/site-session';
            jar.setCookie(authCookie, sessionOptions.uri);
            sessionOptions.jar = jar;
            sessionOptions.method = 'POST';
            return request(sessionOptions)
        })
        .then(function (sessionResponse) {
            var authFound = false,
            cookies = sessionResponse.headers['set-cookie'].slice();

            if (sessionResponse.statusCode === 201) {
                cookies.forEach(function (item) {
                    if (item.indexOf('LWSSO_COOKIE_KEY') !== -1) {
                        authFound = true;
                    }
                });
 
                if (!authFound) {
                    cookies.push(authCookie);
                }
 
-               deferred.resolve(cookies);
+               return cookies;
            } else {
                throw response.statusCode; // Or whatever you want to do in this case
            }
        })
        .catch(function (err) {
            console.log(err);
-           deferred.reject(err);
+           throw err; // Or drop the whole catch block
        });
-   return deferred.promise;
};
```

I hope this helps. But most importantly let me know if you still get the warning.

**Comment by RobHarrisAZ** [comment]
Returning the second promise solved the warning.  And I like the direction of the refactors so I'm working those in as well.  Thanks for taking the time and thanks for the library.

**Comment by analog-nico** [comment]
Great, good to know it is resolved. And you are welcome of course!
