### ISSUE TITLE
@request/promise-core npm install error

### ISSUE THREAD

**Issue by tehChromic** [request/request-promise#141]
I can't install request-promise

npm install --save request-promise

produces:

 Invalid name: "@request/promise-core"

npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

**Comment by analog-nico** [comment]
Do you happen to use an NPM proxy? We [discussed in #137](https://github.com/request/request-promise/issues/137) how to fix that.

Other than that I have not enough info about your environment to guess the cause. However, it is most likely about the support of [scoped packages](https://www.npmjs.org/doc/misc/npm-scope.html). Maybe that helps you with further googling... Let me know if you have more to tell!

**Comment by cabrinoob** [comment]
Hi,
I have the same problem here. It's working perfectly on my local machine, but when I try to install it through a Dokerfile I have the 404 error

In my Dockerfile I tried to call like this : 

> FROM readytalk/nodejs
> 
> WORKDIR /home/nodeapp
> ADD package.json /home/nodeapp
> RUN npm config set "@request:registry" https://registry.npmjs.org/
> RUN npm install @request/promise-core
> RUN npm install
> ADD . /home/nodeapp
> 
> EXPOSE 8080
> CMD ["node","server.js"]

But I always have the 404 error.

**Comment by cabrinoob** [comment]
I succeed in running it by changing my Dockerfile like this : 

FROM readytalk/nodejs

WORKDIR /home/nodeapp
ADD package.json /home/nodeapp
RUN npm install request @request/promise-core
RUN npm install
ADD . /home/nodeapp

EXPOSE 8080
CMD ["node","server.js"]

And my package.json 

> "dependencies": {
> "async": "^2.0.1",
> "body-parser": "^1.15.2",
> "express": "^4.14.0"
> }

So, I remove request and request/promise-core from my package.json dependencies and install it through RUN npm install command of my Dockerfile. It's not very clean but it's working like this ... strange problem indeed.

**Comment by analog-nico** [comment]
I just published `request-promise@4.1.1` which fixes this issue for good.

The number of bug reports in this issue and elsewhere piled up way too high so I renamed `@request/promise-core` to `request-promise-core`. Sorry guys, I didn't anticipate that scoped packages produce that much hassle...

**Comment by cabrinoob** [comment]
No problem, thanks a lot! ;)

**Comment by xinsamwan** [comment]
@analog-nico 
I'm new to nodejs, I try to npm install parse-server, but I have this error Invalid name: "@request/promise-core", do you know how I can fix it?

**Comment by analog-nico** [comment]
@xinsamwan Just upgrade to `request-promise` to version 4.1.1.
