### ISSUE TITLE
source.on is not a function

### ISSUE THREAD

**Issue by OChing43** [request/request-promise#145]
```
const request = require('request-promise');
const req = require('request')
const fs = require('fs');
const FormData = require('form-data')

function readImage(){
    return new Promise(function(resolve, reject) {
        fs.readFile('./img/150150.gif', (err, data) => {
            if(err) reject(err);
            resolve(data);
        });
    });
}

readImage().then(data => {
    let dat = toArrayBuffer(data);
    let filename = new Date().getTime();
    let formData = new FormData();
    formData.append('imageClass', 'twitterApp');
    formData.append('X-Requested-With', 'Iframe')
    formData.append('X-HTTP-Accept', 'application/json, text/javascript, */*; q=0.01')
    formData.append('file', dat, "twitterLogo");
    request.post({url: 'example.com/api/images/', data: dat, processData: false, contentType: false, type: 'POST'}).then(data => {
        console.log(data)
    }).catch(err =>{
        console.log(err);
    })
}).catch(error => {
    console.log(error);
})


function toArrayBuffer(buf) {
    var ab = new ArrayBuffer(buf.length);
    var view = new Uint8Array(ab);
    for (var i = 0; i < buf.length; ++i) {
        view[i] = buf[i];
    }
    return ab;
}
```

request.post says that source.on is not a function, though, I have no idea why that'd be. This is attempting to send an image file.

**Comment by analog-nico** [comment]
Based on the `request`'s README about [how to use streaming](https://github.com/request/request#streaming) you may just do:

``` js
const request = require('request-promise');
const fs = require('fs');

fs.createReadStream('./img/150150.gif').pipe(
    request.post('http://example.com/api/images/')
        .then(data => {
            console.log(data);
        }).catch(err => {
            console.log(err);
        })
);
```

I hope this helps. Otherwise let me know so we can take a closer look why your code produces the error you reported.

**Comment by OChing43** [comment]
I tried that with request (non promise), there were no errors thrown, but the server doesn't actually accept the data, for some reason.
`fs.createReadStream('./img/150150.gif').pipe(request.post('https://example.com/api/images').on('error', err => {throw err})).on('error', err => {throw err});`

**Comment by analog-nico** [comment]
Btw, my code was wrong. I updated it. See above. With that you should now get the same behavior as with `request` (non promise).

If you use the code with streaming it certainly comes with some default settings. You may need to change them. What is the actual error response of your server?

**Comment by OChing43** [comment]
It's not throwing any error response, which is strange. But when I check what it was supposed to do, which is add an image to an array, it doesn't seem to have done it.

**Comment by analog-nico** [comment]
Sorry, I would need more information to help you. But I can give you more thoughts:

- Does the code you initially posted work with `request` (non-promise)? If yes, what is the stack trace you get when running it with `request-promise`?

- To get more insight into what is actually going on for your request with streaming, activate [debugging](https://github.com/request/request-promise#debugging). However, I just realize that you seem to upload to an endpoint for a regular http form. This way of streaming assumes that the endpoint is designed just for uploading files.

- Alternatively, you may use the technique that is described in `request`'s README for [form handling](https://github.com/request/request#forms):

``` js
const request = require('request-promise');
const fs = require('fs');

request.post({url:'http://service.com/upload', formData: {
    file: fs.createReadStream('./img/150150.gif'),
    // ...and all other form inputs
    imageClass: 'twitterApp' // etc.
}})
    .then(data => {
        console.log(data);
    }).catch(err => {
        console.log(err);
    });
```

**Comment by nmccready** [comment]
#1495 related?

**Comment by analog-nico** [comment]
Hey @OChing43 , I just debugged your code at the top. The error occurs in the line `formData.append('file', dat, "twitterLogo");` because `dat` is of type `ArrayBuffer` but the `form-data` library thinks it is a stream. So the issue is with `form-data` without `request-promise` even being involved at this point. Anyways, please note that `form-data` officially only supports strings, streams, and `Buffer` – not `ArrayBuffer`.

If you e.g. change `ArrayBuffer` to `Buffer` you should be good to go.

My last suggested code snippet with `formData: { file: fs.createReadStream(...) }` should also work.

**Comment by ketantada** [comment]
I am getting error: 
`
 TypeError: source.on is not a function
    at Function.DelayedStream.create (/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/node_modules/combined-stream/lib/combined_stream.js:44:37)
    at FormData.append (/node_modules/form-data/lib/form_data.js:74:3)
    at appendFormValue (/node_modules/request/request.js:323:21)
    at Request.init (/node_modules/request/request.js:334:11)
    at new Request (/node_modules/request/request.js:128:8)
    at request (/node_modules/request/index.js:53:10)
`
My code is: 

```
var options = {
  url: 'http://...',
  method: 'POST',
  formData: {
    file: fs.createReadStream(__dirname + '/file.jpg'),
    first_name: 'first_name'
  }
}
request(options, function() {})
```

`Request Version: request@2.85.0`
`node version: node v9.8.0`

**Comment by stuart-clark-45** [comment]
For others coming to this late adding the following header resolved this for me
```
"Content-Type": "multipart/form-data"
```
