### ISSUE TITLE
how will tramsform function accept raw binary data instead of string body

### ISSUE THREAD

**Issue by morfies** [request/request-promise#146]
Hi, my use case is:
I'm getting a page with Chinese chars in it, I use `transform(body)` to get the body and load it by cheerio.
But the `body` is already a string, I cannot recover it with a gbk encoding,  is there a way to get the raw data in the transform function?

Thanks.

**Comment by analog-nico** [comment]
When using `request-promise` please also consider the documentation of `request`. In particular, the [`encoding` option](https://github.com/request/request#requestoptions-callback) is probably what you just need to set.

Hope this helps.

**Comment by morfies** [comment]
Oh really, you are awesome, thanks
All I need is set the `encoding: null`.

**Comment by analog-nico** [comment]
😃 You are welcome!
