### ISSUE TITLE
Doesn't follow 301 redirects using proxy

### ISSUE THREAD

**Issue by morfies** [request/request-promise#151]
Hi, I have to urls:
`http://tbphoto3.bababian.com/upload7/fuguirenshen/201606/001169212894_m.jpg` which is 301 redirected
and `http://t.shuaishou.com/Get/168062675` which is 302 redirected.

But when I request to get the two with 
```js
request.defaults({
  proxy: 'my-proxy-address'
})
```
only 302 redirect is returned successfully with final content.

Any ideas?

**Comment by analog-nico** [comment]
Are you aware of the [`followAllRedirects` option](https://github.com/request/request#requestoptions-callback)? If you are doing POST requests you probably need to set it to `true`.

Anyhow, I am not familiar with all the options in detail. However, if you don't find a solution you may ask the `request` community directly. `request-promise` adds primarily the promise capabilities. The requests themselves are processed by `request` and you may use all its options with `request-promise` as well.

**Comment by morfies** [comment]
I tried the option, but without luck.
The `request` community seems too busy.
Thanks anyway

**Comment by analog-nico** [comment]
I just realized that both requests are followed when you don't use the proxy. But only the 301 not if you use the proxy. That means your request options should be fine.

One tip: Activate [the debugging output](https://github.com/request/request-promise#debugging) to see which requests are sent without and with the proxy to understand what is happening and where it goes wrong.
