### ISSUE TITLE
Nested query strings urlencoded?

### ISSUE THREAD

**Issue by enricodeleo** [request/request-promise#153]
Hi,

I tried some query strings where I have a nested array of queries. Everything I try something like this I get a query urlencoded (with % characters) but I actually need something like[that]. Is there any solution besides require https://github.com/ljharb/qs ?

**Comment by analog-nico** [comment]
Since the `qs` parameter is stringified by the `request` library under the hood, see the [`request` options](https://github.com/request/request#requestoptions-callback) in regard to all options beginning with "qs". In particular, the description for `useQuerystring` should help.

**Comment by enricodeleo** [comment]
Thank you so much for this hint, it was  what I was searching for. Now nested query strings are handled correctly and everything works fine. 

This is the option to declare for such behavior:

```
qsStringifyOptions: {
   encode: false // do not encode arrays within query strings
},
```

**Comment by analog-nico** [comment]
Sweet! Thanks for postimg the solution for all visitors who find this through Google.
