### ISSUE TITLE
Passing data between multiple requests run in series (chaining)

### ISSUE THREAD

**Issue by carlskii** [request/request-promise#155]
Is it possible to provide an example for sequencing (chaining) HTTP POST requests in series and passing the data retuned down the chain. I'm really struggling to find a working example here.

**Comment by analog-nico** [comment]
There are many ways how to do that since we are talking about the more general concern of chaining promises. Just google ["chaining promises"](https://www.google.com/search?q=chaining+promises) and you'll find good articles.

A very simple solution to get you started is:

``` js
var rp = require('request-promise')

rp.post(...)
    .then(function (responseFromFirstPost) {
        var options = { /* copy stuff from responseFromFirstPost */ }
        return rp.post(options) // The return is important
    })
    .then(function (responseFromSecondPost) {
        // ...
    })
```

**Comment by carlskii** [comment]
Thanks for this, and your example is sort of working. However, Im hitting this problem. 

[http://stackoverflow.com/questions/39633709/chaining-http-requests-in-electron-using-request-promise](url)

I'm guessing because everything is running asynchronously.

**Comment by analog-nico** [comment]
I see, that your question got answered on StackOverflow. Perfect!
