### ISSUE TITLE
Global Authorization Token

### ISSUE THREAD

**Issue by Serboy** [request/request-promise#158]
Hi Madam/Sir
  How to setup authorization bearer globally? 

Thanks,

**Comment by analog-nico** [comment]
You seem to already know how to use bearer tokens in a single request, right? Then the last missing piece is the [`.defaults(...)` function](https://github.com/request/request#requestoptions-callback).

**Comment by analog-nico** [comment]
Hi @Serboy , I think it is safe to close this issue now. But feel free to reopen it if you still have questions.

**Comment by Serboy** [comment]
Sure sire, forgot to close this, sorry about that, Thanks a lot

**Comment by analog-nico** [comment]
No problem. Have a great day!
