### ISSUE TITLE
Possible memory leak via stealthy require?

### ISSUE THREAD

**Issue by jeromecovington** [request/request-promise#163]
I'm chasing down a memory leak in my app. Upgrading from `request-promise` 1.0.2 to 4.1.1 seems to have alleviated much of that, but I am concerned about possible leaks via `stealthy-require`, per https://github.com/analog-nico/stealthy-require/issues/2

Can anybody speak to whether `request` is "stealthy required" per request, and whether the issue is a potential problem?

**Comment by analog-nico** [comment]
Yes, `request` is "stealthy required" by `request-promise`. But only once if you call `require('request-promise')`. The issue you referenced is not relevant for `request-promise`. It just can't be the cause of leaked memory piling up.

Did you do some memory profiling? Here are some helpful resources:
- [Simple Guide to Finding a JavaScript Memory Leak in Node.js](https://www.alexkras.com/simple-guide-to-finding-a-javascript-memory-leak-in-node-js/)
- [llnode for Node.js Memory Leak Analysis](http://www.brendangregg.com/blog/2016-07-13/llnode-nodejs-memory-leak-analysis.html)

**Comment by jeromecovington** [comment]
Awesome, thanks very much for your comment @analog-nico, and for the links!

**Comment by analog-nico** [comment]
You are welcome! Please let me know if you find some memory leaks related to `request-promise`.
