### ISSUE TITLE
Where is Promise in request-promise?

### ISSUE THREAD

**Issue by wzup** [request/request-promise#164]
I can't understand where is a `promise` in a `request-promise`. How do I get a `promise` object, not a `Request` object?

```
let rp = require('request-promise');

let p = rp('https://example.com/');

console.log('p', p);

// p is not a promise, it is Request!
Request {
  domain: null,
   ...
     _sessionCache: { map: {}, list: [] } } }
```

How do I get a `promise` object? I need it to create an array of promises. But instead I get an array of Requests.

```
    Object.keys(array).map(id => {
        return rp('https://example.com/' + id); // I expect this to be a Promise, not a Request
    });
```

**Comment by analog-nico** [comment]
Hi @wzup , it is actually both!

What you get is the original request object plus `.then(...)`, `.catch(...)`, and `.finally(...)` attached. If you want to use `request(...).spread(...)` for example then do this: `request(...).promise().spread(...)` But if you just need standard promise capabilities like in your use case with `map` you can work with `rp('https://example.com/' + id)` directly since the returned object has a `.then(...)` method.

Further details see [here](https://github.com/request/request-promise#api-in-detail).

Anything else I can answer for you?

**Comment by BentOnCoding** [comment]
I have the same question. I want the bluebird promise. 

I am coding in typescript, and your return type is RequestPromise which is not castable to a Promise Interface as defined in the spec.
<img width="1046" alt="screen shot 2016-12-17 at 4 30 00 pm" src="https://cloud.githubusercontent.com/assets/23059510/21290400/41b25fca-c476-11e6-86e6-ea8f7fd61724.png">

Is there a way to access the raw promise returned from bluebird?

**Comment by analog-nico** [comment]
@BentOnCoding Yes there is: [`rp(...).promise()`](https://github.com/request/request-promise#promise---for-advanced-use-cases)

**Comment by wzup** [comment]
@analog-nico 

What do you mean?
> _you can work with rp('https://example.com/' + id) directly_ 

How is it "_work directly_"? Isn't my example not "_a work directly_"?
```
    Object.keys(array).map(id => {
        return rp('https://example.com/' + id); // I expect this to be a Promise, not a Request
    });
```
Is there some "more directly way"? Could you please provide an example.

**Comment by analog-nico** [comment]
@wzup Oh true, my wording was unclear. Your code is already "working directly" with the object returned by `rp(...)`. "Not working directly" would be using `return rp(...).promise();` which would work as well but is unnecessary.

I think that wraps up this issue. But feel free to ask follow-up questions if you have any.

**Comment by Lancer92** [comment]
> Hi @wzup , it is actually both!
> 
> What you get is the original request object plus `.then(...)`, `.catch(...)`, and `.finally(...)` attached. If you want to use `request(...).spread(...)` for example then do this: `request(...).promise().spread(...)` But if you just need standard promise capabilities like in your use case with `map` you can work with `rp('https://example.com/' + id)` directly since the returned object has a `.then(...)` method.
> 
> Further details see [here](https://github.com/request/request-promise#api-in-detail).
> 
> Anything else I can answer for you?

Have you tried to use `sonarlint`? It shows error on `rp(...)`:
`Refactor this redundant 'await' on a non-promise. `
But fine with `rp(...).promise()`
