### ISSUE TITLE
No return on Windows and Node v7.1.0?

### ISSUE THREAD

**Issue by paulxtiseo** [request/request-promise#166]
The script below comes to a complete and silent stop at line 28 specifically under node v7.1.0 in Windows. No error, no exception, no stack dump, just a silent drop out to the command line as if nothing devastatingly horrible had just been perpetrated. :)

If I backtrack the node version to v7.0.0 or earlier, it works. Same script also works as expected on a Mac, in v7.1.0.

The `console.log(res)` on line 27 does execute, but the return seems to never happen properly; line 31-32 with `console.log('\n\nvoteds', voteds);` never shows an array built from `map()` on line 17. Also, the `catch()` and `finally()` never execute.

Any suggestions?

```
/* jslint node:true, esversion:6 */
'use strict';

const _        = require('lodash');
const promise  = require('bluebird');

const fs       = promise.promisifyAll(require('fs'));
const rp       = require('request-promise');

fs.readFileAsync('emails.txt', 'utf8')
  .then(function(file) { // read file into an array
    //console.log('file', file);
    return promise.map(file.split('\r\n'), line => {
      return { Agent: null, VoterID: null, Email: line, IsVerified: null };
    });
  })
  .map(function(email) {
      //console.log('email', email);
      let options = {
          uri: '...',
          method: 'POST',
          body: { email: email.Email },
          json: true 
      };
      return rp(options)
        .then(function(res) { 
          console.log(res); 
          return res;
        });
  })
  .then(function(voteds) {
    console.log('\n\nvoteds', voteds);
  })
  .catch(function(err) {
    console.error('\n\nERROR', err);
  })
  .finally(function() { 
    console.log('\n\ndone!'); 
  });
```

**Comment by paulxtiseo** [comment]
Also, if I replace `return res;` with `return 'yay!'`, I get an expected array of happiness. Not sure why the return on the promise causes some mysterious silent halt under Win + node v7.0.1?

**Comment by analog-nico** [comment]
That is a weird quirk to say the least. My first guess would be `bluebird`'s internal handling of the return value.

A few things you can check:

- Type `npm list bluebird` to ensure that both your project and `request-promise` are using the latest version of `bluebird`.
- For a quick test you may use `return new Promise(function (resolve) { resolve(res); })` - whereas `Promise` is the native Promise implementation - instead of `return res` to see the promise chain is able to digest `res` this way.

**Comment by paulxtiseo** [comment]
```
E:\Repositories\Node\Scripts\Voter>npm list bluebird
voter@1.0.0 E:\Repositories\Node\Scripts\Voter
`-- bluebird@3.4.6
```
if I replace the return at line 28:
```
          return new Promise(function (resolve) { resolve(res); })
          //return res;
```
I still get no data returned.
```
E:\Repositories\Node\Scripts\Voter>node test.js

E:\Repositories\Node\Scripts\Voter>
```

**Comment by analog-nico** [comment]
These results plus the fact that `return 'Yay!'` works, makes me wonder about the `res` object. Is this a particular big object? Or anything special?

You could also try `return _.cloneDeep(res);` instead of `return res;` to make sure no special data type is included. (Lodash would filter them out.)

**Comment by paulxtiseo** [comment]
I'm exploring https://github.com/nodejs/node/issues/9542 as a possible reason, with help from a Gitter user(@not-an-aardvark on petkaantonov/bluebird) given the specificity of the error wrt to the node version and environment, there must be a regression or a bug introduced.

**Comment by analog-nico** [comment]
Btw, you may slim down the test case a bit (only native Promises, no map etc.) and run it with `request-promise-native`. This will allow you to find out if `bluebird` has anything to do with it.

**Comment by analog-nico** [comment]
Hey @paulxtiseo , did you find the cause of this issue?

**Comment by paulxtiseo** [comment]
If I remember correctly, and I am 98% sure, upgrading Node to v7.2.0 fixed it.

**Comment by analog-nico** [comment]
Thanks, good to know!
