### ISSUE TITLE
.catch(function(error) { } ) - Error is response object

### ISSUE THREAD

**Issue by mick0n** [request/request-promise#170]
I have an application which utilizes request-promise to fetch content from different webservers. Problem is, sometimes I get an error page back from the webserver, sent with statuscode 500, which ends up in my .catch-function but with a response object as error, not an actual error.

I would expect a catch-function to always have an error object as its only parameter.

**Comment by analog-nico** [comment]
`request-promise` actually does always return `Error` objects. Here is [a list](https://github.com/request/promise-core/blob/master/lib/errors.js) of all error types. All of them, however, contain the `response` as an attribute. Could that be the reason for a misunderstanding maybe?

**Comment by mick0n** [comment]
I will have to double check that on monday, but I don't remember seeing any error-related properties on the input to the catch-function.

**Comment by mick0n** [comment]
I stand corrected, it was indeed an error object containing the response. Thank you for the help :-)

**Comment by analog-nico** [comment]
You are welcome. Have a great week!
