### ISSUE TITLE
path substitution on remote site 

### ISSUE THREAD

**Issue by rlnit5** [request/request-promise#172]
My remote URL is like http://remote.site/rest/json/{path1}/something/{path2} . How do I substitute both path parameters?

**Comment by analog-nico** [comment]
It sounds like you are asking about how to do string concatenation:

``` js
var path1 = 'some-path-1'
var path2 = 'some-path-2'

// ES5
var remoteUrl = 'http://remote.site/rest/json/' + path1 + '/something/' + path2

// ES6
let remoteUrl = `http://remote.site/rest/json/${ path1 }/something/${ path2 }`
```

Please correct me if I misunderstood your question.

**Comment by analog-nico** [comment]
Hey @rlnit5 , I think it's safe to close this issue now. But feel free to reopen it if you still have questions.
