### ISSUE TITLE
Proxy default not working

### ISSUE THREAD

**Issue by SparkleOff** [request/request-promise#173]
The whole request works, but how i know the proxy isn't working is because the site that i am sending the request to calls back with needing a captcha. I have it choose from a whole list of proxies but this is just how i am using the function.

This is how i have it set up:

var request = require('request-promise').defaults({
    proxy: "http://ip:port",
    pool: {maxSockets: Infinity},
    simple: false,
    gzip: true
  });

**Comment by SparkleOff** [comment]
Sorry this seems to be a problem on my side because i did test on an ip get site and it seems to be getting the proxy instead of my server's IP.

**Comment by analog-nico** [comment]
No problem.

Btw, the automated tests ensure that the parameters work correctly. And all [proxy options](https://github.com/request/request#proxies) available for `request` are available for `request-promise` as well.

I am closing this issue but feel free to ask follow-up questions.
