### ISSUE TITLE
"message":"503 - NOT OK","name":"StatusCodeError"

### ISSUE THREAD

**Issue by KabeloShongwe** [request/request-promise#176]
Please assist if you have once came across this error.

**Comment by analog-nico** [comment]
Hi @KabeloShongwe , the 503 error - as all 5xx errors - are errors that occur on the server side. Your request has nothing to do with it. If there was something wrong with your request then you would get a 4xx error. Of course there is still a chance that something is wrong with your request but this would mean that your server doesn't send a proper error code back. Either way you have to study the particular server you are calling to see why you are getting this error.

If the api docs of your server don't give you the info you need it is best you get in touch with the community of that server.

I hope this helps.

**Comment by KabeloShongwe** [comment]
Thank you so much
