### ISSUE TITLE
[help] Response as utf8

### ISSUE THREAD

**Issue by mateusduraes** [request/request-promise#177]
Hello, i believe it is not a problem with request-promise, but, here we go haha.
I have a nodejs crawler using request-promise and my problem is about the html response...

I get some elements in the body and then i console.log they, but, i get this character �
instead any special character.

So... is there a way in request-promise to set html response as utf8 ?
here is my code
https://github.com/mateusduraes/crawler-br-news/blob/master/index.js

If something is wrong, sorry me, im new in gh.
Thank you.

**Comment by analog-nico** [comment]
Hi @mateusduraes , `request-promise` is built on top of `request` and thus the documentation of `request` applies as well. It documents a [`encoding` option](https://github.com/request/request#requestoptions-callback) that you can set. However, it is utf8 by default.

By looking at your code I don't think the encoding is the issue. It's rather that you lost the implicit binding of the `log` function to the `console` object. (If you don't understand what I mean please google implicit vs. explicit binding in javascript.)

The solution might be:
``` diff
  requestPromise('http://www.em.com.br/')
    .then(getNews)
    .then(prettyjson.render)
-   .then(console.log)
+   .then((result) => {
+     console.log(result)
+   })
```

Hope this helps!

**Comment by analog-nico** [comment]
May I close this issue or is there anything I can help you with?

**Comment by mateusduraes** [comment]
Hello bro, thanks for the suggestion but it doesn't worked.
By the way i still trying to find the solution, and yes, you can close the issue.
Thanks for the attention!
