### ISSUE TITLE
Does this module support Gzip decoding. ?

### ISSUE THREAD

**Issue by arihantdaga** [request/request-promise#178]

**Comment by analog-nico** [comment]
Yes, it does. Since `request-promise` is built on top of `request` you can use all options of `request` as well. Please refer to the `gzip` option in the [`request` docs](https://github.com/request/request#requestoptions-callback).

**Comment by arihantdaga** [comment]
ohk...this works great..

**Comment by analog-nico** [comment]
Perfect! Happy coding. :)
