### ISSUE TITLE
Download files through GET request?

### ISSUE THREAD

**Issue by divye01** [request/request-promise#179]
Hello,

I am trying to download a csv from PHP server. However, request-promise resolves the file to json even when the json field is set to false in the request. Is there any way I can download files through request-promise?

Thanks!

**Comment by analog-nico** [comment]
Yes, you can.

However, if your files are large then consider using `request` and streams (`.pipe(...)`). With `request-promise` the whole file will be in memory which has an impact on your memory footprint. Decide that based on how much memory (RAM) your server has and how big the csv file might be.

If you go ahead with `request-promise` please show me your code snippet so I can give you some feedback.

**Comment by analog-nico** [comment]
Hey @divye01 , I think it is safe to close this issue now. But feel free to reopen it if you want to continue our discussion.
