### ISSUE TITLE
better stacktraces

### ISSUE THREAD

**Issue by kilianc** [request/request-promise#184]
Since I started using `await` and this module my life got soooo much better. This said, I completely lost stacktraces, I can't tell the line in my code that's throwing this error and therefore my code becomes a bunch of `console.log`s like it's 1998.

Also, when this happens in production you just try to guess what's wrong.

Example:
```
StatusCodeError: 404 - Page not found
at StatusCodeError (/opt/node_modules/request-promise-core/lib/errors.js:32)
at Request.plumbing.callback (plumbing.js:104)
at Request.RP$callback (/opt/node_modules/request-promise-core/lib/plumbing.js:46)
at Request.self.callback (request.js:186)
at emitTwo (events.js:106)
at Request.emit (events.js:191)
at Request.<anonymous> (/opt/node_modules/request/request.js:1060)
at emitOne (events.js:96)
at Request.emit (events.js:188)
at IncomingMessage.<anonymous> (/opt/node_modules/request/request.js:980)
at IncomingMessage.g (events.js:291)
at emitNone (events.js:91)
at IncomingMessage.emit (events.js:185)
at endReadableNT (_stream_readable.js:974)
at (/opt/node_modules/async-listener/glue.js:188)
at _combinedTickCallback (internal/process/next_tick.js:74)
```

Is there anything we can do to improve this? I am not even sure this is a problem with `request` or `request-promise-*`

<3

**Comment by analog-nico** [comment]
Hi @kilianc , indeed stacktraces are a drawback when using promises. You could look into using so called “long stacktraces” that track the code lines across async hops but it slows down the code and therefore it is not a good solution for production code.

However, could you give me more details about to what extend you lost stacktraces? Did you use `request-promise` with traditional promise handling and still had stacktraces? Or did you switch from using `request` with callbacks directly to `request-promise` with `await`? Also, do you run it in node or do you run it in the browser + babel?

Debugging your production errors is indeed nothing `request-promise` is responsible for. You need to write some error handling code that helps you with the unique requirements of your application. The first thing you can do is to access `err.response` to get the full response which also includes `err.response.request`. But keep in mind that the `.request` data structure is an internal data structure of the `request` library and can change anytime. A safe alternative to `err.response.request` is `err.options`. These are the options you initially passed to the request. In my own application I have specific points in my code where I catch errors and wrap them into application specific errors that contain more information about e.g. the module/task in which the error occurred. Only after I wrapped the error I then send it to the general error monitoring subsystem.

**Comment by jaredbiehler** [comment]
In hindsight this seems obvious, but in case this helps anyone else, I was also having a problem where my traces were seemingly useless until a fellow co-worker pointed out that I should `await` before returning inside the try / catch.

I get a useful trace from: 
```        
try {
    return await request(options);
} catch (error) { throw new CustomError(...); }
```
whereas I get a trace similar to the one above from: 
```        
try {
    return request(options);
} catch (error) { throw new CustomError(...); }
```

**Comment by analog-nico** [comment]
Thanks for the info @jaredbiehler !
