### ISSUE TITLE
POST does not return any response on 2xx return

### ISSUE THREAD

**Issue by dylanh724** [request/request-promise#186]
Discord webhooks, for example, return only a 204. 

In the original request, it returns a **(err, response, body)**

However, request-promise only returns **(parsedBody)** -- and there is no body! They just sent back a code with some header info. I would like to see at least the response code (originally **response.statusCode**).

How can I get the statusCode, etc on a POST return?

**Comment by analog-nico** [comment]
Check out the [`resolveWithFullResponse` option](https://github.com/request/request-promise#fulfilled-promises-and-the-resolvewithfullresponse-option) and its use in [this example](https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body).

Does this solve you issue?
