### ISSUE TITLE
How to hit api using proxy

### ISSUE THREAD

**Issue by hgupta210** [request/request-promise#190]
Is there any way in request-promise module to hit an api endpoint through a proxy setup. If anyone has any  idea or done this, please help me.

Thanks,
Hitesh

**Comment by analog-nico** [comment]
Hi Hitesh, yes there is. `request-promise` is built on top of `request` and `request` is the library that does all the heavy lifting. Thus you can look up all the available features in the `request` docs. In particular, here is [how you use a proxy](https://github.com/request/request#proxies). Let me know if that helped.

**Comment by hgupta210** [comment]
Thanks, could you also refer me to some working example or configuration to be used. I basically wants to hit an API through a proxy and want to see if the traffic passes through that proxy server.

**Comment by analog-nico** [comment]
@hgupta210 That is something the `request` community will be able to give you. Since `request` is so widely used you’ll probably find one by just googling. All examples will work with `request-promise` as well.

If you find one it would be great if you leave a link here so that other users who come across this issue can benefit from that. Thanks!

**Comment by lorux** [comment]
i used 
```
  var request = require('request-promise').defaults({
    proxy:'http://username:password@host:port',
    strictSSL :false
  });
```

**Comment by jjoocceeee** [comment]
Here is example usage: https://github.com/request/request/issues/894

**Comment by analog-nico** [comment]
For any one finding this issue, you can do requests through proxies by following the [instructions for `request`](https://github.com/request/request#proxies). It works the same way for `request-promise`.
