### ISSUE TITLE
Async/Await not working for some reason. 

### ISSUE THREAD

**Issue by kati-frantz** [request/request-promise#194]
This library should work with async/await, but for some reason my tests using mocha ( on nodejs ) spit out the famous `Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Prom
ise, ensure it resolves.`

```js

const Post = require('./Post')
const assert = require('chai').assert
const request = require('request-promise')


describe('The posts api', () => {
      it('Should return a post listing ', async () => {
            let post = {
                  title: 'some title',
                  body: 'some body for first post'
            }
 
            const newPost = await (new Post(post)).save()      

            const responsePost = await request.get(`http://localhost:5432/api/posts/${newPost.id}`)
            
            assert.equal(newPost.id, responsePost.body.id)   
      })
})


```

What did I do wrong in my code? And how could I write this test better so it works with the request-promise library and async/await

**Comment by analog-nico** [comment]
Hi @kati-frantz , your code looks good to me. Can you try the following code to see if the test now succeeds?

``` diff
const Post = require('./Post')
const assert = require('chai').assert
-const request = require('request-promise')
+const Bluebird = require('bluebird')


describe('The posts api', () => {
      it('Should return a post listing ', async () => {
            let post = {
                  title: 'some title',
                  body: 'some body for first post'
            }
 
            const newPost = await (new Post(post)).save()      

-           const responsePost = await request.get(`http://localhost:5432/api/posts/${newPost.id}`)
+           const responsePost = await Bluebird.resolve({ body: { id: newPost.id } })
            
            assert.equal(newPost.id, responsePost.body.id)   
      })
})
```

**Comment by kati-frantz** [comment]
@analog-nico thanks for checking this out. I ran the code, but the same result. Same old Timeout error . Then I decided to try out something simpler. 

```js

const Post = require('./Post')
const assert = require('chai').assert
const Bluebird = require('bluebird')


describe('The posts api', () => {
      it('Should return a post listing ', async () => {
            let post = {
                  title: 'some title',
                  body: 'some body for first post'
            }
 
            const response1 = await Bluebird.resolve(1 + 2)   

            const response2 = await Bluebird.resolve(2 + 1)            
            assert.equal(response1, response2)   
      })
})

```

And the tests actually run till the end , and the assertions are made, and the test passes. This makes me think that the first promise ( `mongoose save()` method ) was not resolving in the first place, causing a time out , and second `await` was not even called. So mayby, for some reason, the problem is with the `mongoose save()` method ?

**Comment by analog-nico** [comment]
Very likely. There is nothing else there that could cause it.

Feel free to reopen this issue if you made the code version in my comment work but the original version with `request.get(...)` still doesn’t.
