### ISSUE TITLE
deprecation warning when using request-promise and cheerio

### ISSUE THREAD

**Issue by afrojezus** [request/request-promise#195]
I get this message that stops the promise from loading on first try:

> Resource requests whose URLs contain raw newline characters are deprecated, and may be blocked in M60, around August 2017. Please remove newlines from places like element attribute values in order to continue loading those resources. 

however, if I reload the same page, the promise works.

here's the promise I'm trying to execute
```js
Rp(source).then(($) => {
          const videoUrl = $('#download').attr('href')

          const videoSource = {
            uri: videoUrl,
            transform: (body) => {
              return Cheerio.load(body)
            }
          }
          return videoSource
        }).catch((err) => console.log(err)).then((videoSource) => {
          Rp(videoSource).then(($) => {
            const episodeLink = $('a.bttn.green:nth-child(4)').attr('href')
            console.log(episodeLink)
            this.setState({video: episodeLink})
          })
        })
```

is there a way to get around this? 
sorry if this question is a bit off

**Comment by analog-nico** [comment]
Well, we could dive into if and where you might need better promise handling but you should attend to the deprecation warning to begin with.

Do you need newlines in your uri?! `videoUrl.trim()` is probably what you need.

**Comment by afrojezus** [comment]
hmm that didn't quite work...

**Comment by analog-nico** [comment]
It seems the warning is coming from V8. For all I know it is just as the message says – you have newlines in your uris. If trim doesn’t work then they are within the uri. Either remove or encode them.

**Comment by afrojezus** [comment]
figured out the URI was being passed as a state from this.props.location (using react-router v4) which made it unusable for some reason. Passing it as a search query works though.

**Comment by analog-nico** [comment]
Awesome!
