### ISSUE TITLE
Autocompleter using request

### ISSUE THREAD

**Issue by bhairavitech** [request/request-promise#196]
I wanted to know, how to replace jQuery autocompleter with request.

function set_customer_autocompleter() {
		$('#customer_name').autocomplete({
			source: '/yuvapos/auto_complete_for_customer_name/',
			minLength: 3,
			autoFocus: true,

			focus: function(event, ui) {
				$("#customer_name").val(ui.item.company_name);
				return false;
			},
			dataType: "json",
			select: function(event, ui) {
				$("#sale_customer_id").val(ui.item.id);
				return false;
			}
		})
		.data("ui-autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
			.data("item.autocomplete", item)
			.append("<a>" + item.company_name + "</a>")
			.appendTo(ul);
		};
	}

Thanks.

**Comment by analog-nico** [comment]
I am sorry @bhairavitech but your question is out of the scope for an issue in this repo. You first have to start with finding out how to replace the part of jQuery that does the requests to the server. If you later have a specific question for `request-promise` feel free to open another issue.
