### ISSUE TITLE
Performance issue: open socket leak

### ISSUE THREAD

**Issue by 0xR** [request/request-promise#197]
I'm running some load tests on [a library](https://github.com/yarax/swagger-to-graphql/blob/master/lib/index.js#L50) using request-promise (4.1.1). During the  load test I get `EMFILE` errors. These are caused by an OS error when there are too many files open. This is caused by having too many sockets open. I ran: `lsof -i -n -P | grep node` to determine this. During the load test it peeks up to to 5k sockets. When I replace `request-promise` with `node-fetch` I don't get this issue.

I can't investigate any further right now, but this might be a serious performance issue which can bring down your production servers easily.

**Comment by analog-nico** [comment]
Interesting. Could you provide a simple test case to replicate the issue?

**Comment by toremielck** [comment]
@analog-nico i second this

**Comment by analog-nico** [comment]
@toremielck Do you happen to have a code snippet to reproduce this issue?

**Comment by analog-nico** [comment]
I would look forward to get more details on this. But for now I have not enough clues to work with unfortunately.
