### ISSUE TITLE
HTTPS: POST request goes to port:80 not port:443 

### ISSUE THREAD

**Issue by maxwell-oroark** [request/request-promise#200]
I am getting an SSL protocol error using your library.  It appears when trying to POST with an options object with property `uri : https://...` it fails to point to the right port.  

As I could not find any additional options related to `https`, I am assuming this is a bug that was introduced to your codebase.

**Comment by analog-nico** [comment]
Well, that is weird. I am doing https calls all the time and it works fine. Which `request-promise` and `request` versions are you using? And can you give me your full request options you are using? Thanks!

**Comment by maxwell-oroark** [comment]
Versions are:

```
    "request": "2.81.0",
    "request-promise": "4.2.1"
```

and options object looks like:

```
   const options = {
      method: 'POST',
      uri: 'https://gbdx-email-invite.herokuapp.com/invite',
      body: {
        account_id: this.props.accountId,
        name: this.state.name,
        email: this.state.email
      },
      headers: {
        'Authorization' : `Bearer ${localStorage.getItem('gbdx_token')}`
      },
      json: true // Automatically stringifies the body to JSON
   };
```

Thanks for the swift reply @analog-nico

**Comment by analog-nico** [comment]
Quick question: Did you consider that Heroku’s load balancer is most likely rerouting https traffic to http traffic? Aka ssl termination. So even https request will arrive as http traffic at your application instance.

**Comment by maxwell-oroark** [comment]
Hmm I did not consider that, let me tell you a few more interesting details.  

This error presented itself only after pushing to production.  At the time, I was trying to go to http://heroku_app because I do not to verify the identity of my own service.  However, it would not let me do this as https:// services cannot make AJAX requests out to less secure sites, I guess. 
So, I switched my call to https://heroku_app and this change gave me the SSL error.  To fix, I simply made the call from the native fetch library and my error went away.  Why did switching to the native fetch implementation get rid of this error?  Is there a way to use your library knowing the insight ^?

**Comment by analog-nico** [comment]
What SSL error did you exactly get?

**Comment by altras** [comment]
We're having the same issue @analog-nico :/ Although we're deploying on AWS, using EC2 with ELB.

We're constructing an url `https://api-stage.rulerapproach.com/rest/rpc/login` which gets translated to a POST request with url`https://api-stage.rulerapproach.com:80/rest/rpc/login` in the networks tab in browser.

This happens on our staging server and not when testing on localhost.

**Comment by analog-nico** [comment]
I assume that this issue is now outdated. Sorry that I didn’t reply in time @altras .
