### ISSUE TITLE
Return response headers on promise rejection

### ISSUE THREAD

**Issue by dyladan** [request/request-promise#202]
I am interacting with an API that uses the `Authorization` header and which redirects to a different host using a 302. `request-promise` appears to strip out the `Authorization` header, which I understand the reasons for. Because of this, however, I have to implement redirection myself. I am catching the promise rejection and checking the error code for `302` and making the request again. The issue I'm running in to is that the API returns the location to redirect to in the `Location` header with an empty body and a `Content-Length: 0`, but the `Location` header is not accessible from the `error` object and `err.response` is undefined. Please make the full response, or at least the response headers, available in the promise rejection.

**Comment by analog-nico** [comment]
Hi @dyladan , you can get the full response by using the [`resolveWithFullResponse` option](https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body). But did you check out all [redirect options](https://github.com/request/request#requestoptions-callback) the underlying `request` library has to offer? E.g. `followOriginalHttpMethod`.

**Comment by dyladan** [comment]
does `followOriginalHttpMethod` stop the Authorization header from being stripped out on a redirect to a different domain?

I tried `resolveWithFullResponse` but the response parameter of the `err` object still is undefined.

**Comment by analog-nico** [comment]
With `{ simple: true }` you can access the full response through `err.response` in the `catch` handler. If it is undefined then the cause lies within your request itself.

With `{ simple: false, resolveWithFullResponse: true }` you get the full response in the `then` handler and you can check the `res.statusCode` yourself.

Try `followOriginalHttpMethod` out. That’s all I can say.

Please read through the documentation. Most likely you find the solution. If you don’t please give me your exact request parameters and the errors you are getting.

**Comment by dyladan** [comment]
With `{ simple: true }`, `err.response` is undefined.

With `followOriginalHttpMethod`, the `Authorization` header is stripped out on redirects to different domains.

Here is my options object:

```
{ uri: 'https://domain/api/v1/method',
  headers: { Authorization: 'REDACTED' },
  json: true,
  timeout: 20000,
  followRedirect: false,
  resolveWithFullResponse: true }
```

Here is the `err` object I get back in the promise rejection

```
{ StatusCodeError: 302 - undefined
    at new StatusCodeError (/Users/danny/playground/davis/old/node_modules/request-promise-core/lib/errors.js:32:15)
    at /Users/danny/playground/davis/old/node_modules/request-promise-core/lib/plumbing.js:97:41
    at tryCatcher (/Users/danny/playground/davis/old/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/danny/playground/davis/old/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/danny/playground/davis/old/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/danny/playground/davis/old/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/danny/playground/davis/old/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/danny/playground/davis/old/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/danny/playground/davis/old/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'StatusCodeError',
  statusCode: 302,
  message: '302 - undefined',
  error: undefined,
  options:
   { uri: 'https://domain/api/v1/method',
     headers: { Authorization: 'REDACTED' },
     json: true,
     timeout: 20000,
     followRedirect: false,
     callback: [Function: RP$callback],
     simple: true,
     resolveWithFullResponse: true,
     transform2xxOnly: false },
  response: undefined }
```

**Comment by dyladan** [comment]
Here is the exact curl output for completeness so you can see exactly what is coming down the pipe.

```
curl -v https://jnc47888.live.dynatrace.com/api/v1/timeseries?relativeTime\=day\&queryMode\=series\&aggregationType\=count\&timeseriesId\=com.dynatrace.builtin:app.useractionsperminute
*   Trying 52.5.49.208...
* TCP_NODELAY set
* Connected to jnc47888.live.dynatrace.com (52.5.49.208) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.live.dynatrace.com
* Server certificate: Trusted Secure Certificate Authority 5
* Server certificate: USERTrust RSA Certification Authority
> GET /api/v1/timeseries?relativeTime=day&queryMode=series&aggregationType=count&timeseriesId=com.dynatrace.builtin:app.useractionsperminute HTTP/1.1
> Host: jnc47888.live.dynatrace.com
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Wed, 21 Jun 2017 18:34:41 GMT
< Location: https://jnc47888.live.dynatrace.com/api/v1/timeseries/?relativeTime=day&queryMode=series&aggregationType=count&timeseriesId=com.dynatrace.builtin:app.useractionsperminute
< Content-Length: 0
< Strict-Transport-Security: max-age=31536000;includeSubDomains
< Set-Cookie: SRV=server6; path=/; HttpOnly; Secure
<
* Curl_http_done: called premature == 0
* Connection #0 to host jnc47888.live.dynatrace.com left intact
```

**Comment by analog-nico** [comment]
Mmh, when I execute this in node v6 with all libraries up-to-date then `err.response` is properly set:

``` js
'use strict'

let rp = require('request-promise')

rp({
    uri: 'https://jnc47888.live.dynatrace.com/api/v1/timeseries?relativeTime=day&queryMode=series&aggregationType=count&timeseriesId=com.dynatrace.builtin:app.useractionsperminute',
    json: true,
    timeout: 20000,
    followRedirect: false,
    resolveWithFullResponse: true
})
    .then(console.dir)
    .catch(console.error)
```

Do you use node, too?

**Comment by dyladan** [comment]
yes I am on node 7.10

**Comment by dyladan** [comment]
Your stripped down example works for me also. There must be something on my end causing it. For the record, I still think the headers should be available in the err.response object. You can close this issue if you want though.

**Comment by analog-nico** [comment]
It would be great if you let me know what was causing `err.response` to be `undefined`!

What do you mean by “header should be available in the `err.response` object”? The response object is about the server’s response. The headers in there are the ones that the server sends. But I guess you are referring to the headers you sent with the request, right? You have to ways to access them: `err.response.request.headers` or `err.options.headers`.

**Comment by dyladan** [comment]
I have a transform function that i'm using that I stripped out of the snippet I sent you that seems to be related. Including it results in an undefined err.response and a promise rejection on 3xx, removing it changes the behavior completely.

```
(body, response) => {
        // Adds response time information to logs
        const path = response.req.path.split('?')[0];
        this.logger.info(`DYNATRACE API: ${path} ${response.statusCode} - ${response.elapsedTime} ms`);
        return body;
      }
```

**Comment by analog-nico** [comment]
Oh, I see. In this case `err.response` is the transformed response. Since you are returning `body` and your response doesn’t have a body you get `undefined`.

The proper implementation is:

``` js
(body, response, resolveWithFullResponse) => {
    // Do logging
    return resolveWithFullResponse || !/^2/.test('' + response.statusCode) ? response : body;
}
```

**Comment by dyladan** [comment]
is resolveWithFullResponse not a boolean in this case? It looks like if resolveWithFullResponse is true it would just return true. Unless it is actually the response object

**Comment by analog-nico** [comment]
The `... ? ... : ...` operator is evaluated after the `... || ...` operator.

**Comment by dyladan** [comment]
ah ok. I incorrectly assumed it would be the other way around

**Comment by analog-nico** [comment]
Haha, no problem buddy.
