### ISSUE TITLE
I often get some RequestError? Why

### ISSUE THREAD

**Issue by zhushichong** [request/request-promise#203]
the errors like    { name: 'RequestError',
     message: 'Error: Parse Error',
     cause: { bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' },
     error: { '$ref': '$["err"]["cause"]' },
     options:
      { uri: 'http://...',
        method: 'GET',
        headers: [Object],
        json: true,
        callback: [Function: RP$callback],
        transform: undefined,
        simple: true,
        resolveWithFullResponse: false,
        transform2xxOnly: false },
     response: undefined } }

   { name: 'StatusCodeError',
     statusCode: 400,
     message: '400 - "<h1>Bad Message 400</h1><pre>reason: Bad Request</pre>"',
     error: '<h1>Bad Message 400</h1><pre>reason: Bad Request</pre>',
     options:
      { uri: 'http://...',
        method: 'GET',
        headers: [Object],
        json: true,
        callback: [Function: RP$callback],
        transform: undefined,
        simple: true,
        resolveWithFullResponse: false,
        transform2xxOnly: false },
     response:
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1

It seems that everything is ok, but sometimes the request errors happen and it happens continuously in a short time. thank for giving some answers

**Comment by analog-nico** [comment]
@zhushichong The first error is caused by an invalid response by your server that does not conform to the HTTP protocol and thus cannot be parsed by node. You have to fix your server for this.

The second one is a perfectly fine request but your server doesn't like your request parameters. You have to adjust your request parameters for that.

**Comment by zhushichong** [comment]
@analog-nico I also got the following error 
   { name: 'StatusCodeError',
     statusCode: 400,
     message: '400 - "<h1>Bad Message 400</h1><pre>reason: Illegal character 0x17</pre>"',
     error: '<h1>Bad Message 400</h1><pre>reason: Illegal character 0x17</pre>',
     options:
      { uri: 'http://api-phx.vip.sankuai.com/cprod/api/v1/homepage/recommend?utm_campaign=AgroupBgroupC876987921729589248_c8_e4585966302555398567_a北戴河_b30205130D300E0Ghomepage_category10_20513__a1__uchuxingcategoryhotel-v5-w2009&utm_content=862124034015011&utm_medium=android&utm_source=xiaomi&utm_term=513&version_name=8.1.3&lng=113.309605&lat=40.028656&ci=129',
        method: 'GET',
        headers: [Object],
        json: true,
        callback: [Function: RP$callback],
        transform: undefined,
        simple: true,
        resolveWithFullResponse: false,
        transform2xxOnly: false },
     response:
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,

The point is that a same request, sometimes wrong, sometimes OK

**Comment by analog-nico** [comment]
@zhushichong You have to take care of the proper encoding of your query parameters. Or even better use the `qs` option and its done automatically.

**Comment by zhushichong** [comment]
@analog-nico The problem is solved after I use encodeURIComponent to encode query parameters.
thx！

**Comment by analog-nico** [comment]
Excellent! Happy coding!

**Comment by guilaoqi** [comment]
I have the same problem,can you explain more detail about how you solved this problem? please~
