### ISSUE TITLE
forever: true option?

### ISSUE THREAD

**Issue by allanchau** [request/request-promise#205]
Is it possible to use `forever: true` with this module? If so, could you point me to an example?
Thanks!

**Comment by analog-nico** [comment]
Yes, you can. `request-promise` uses `request` under the hood and therefore works the same. It seems to me you already know how to do that with `request`. You don’t need to do anything different for `request-promise`.

**Comment by allanchau** [comment]
cool, thanks 👍

**Comment by analog-nico** [comment]
You are welcome. Happy coding!
