### ISSUE TITLE
Force closing connection to proxy server

### ISSUE THREAD

**Issue by yourfavorite** [request/request-promise#208]
I use a proxy server that limits the number of simultaneous connections I can make to it. Say for example the number is 10. I run 10 requests through the proxy server. Each time I get the response body of a request, I then fire off a new request using the same proxy server. 

This works fine it would seem but from time to time I get a very slow proxy connection to the server, so I have an 8 second timeout that calls the cancel() method and then fires off the request again. When this happens, I start to get refused/reset connections from the proxy server which leads me to believe that the connection to the proxy server isn't actually getting closed with cancel(); Is there a way that I can check this or a way that I can forcefully close the connection to the proxy server?

**Comment by analog-nico** [comment]
Well, [`.cancel()`](https://github.com/request/request-promise#cancel) invokes the [low level node function](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_request_abort) to abort the request. I don’t see any other way this can be done. But proof me wrong.

I would start using one of the ways to [debug your requests](https://github.com/request/request-promise#debugging). Maybe even monitor the TCP traffic with WireShark.

**Comment by yourfavorite** [comment]
Thanks Nico. I have run the request with debug and this is essentially the sequence I get.

Complete request
```
REQUEST {}
REQUEST make request *url*
REQUEST onRequestResponse *url* 200
REQUEST reading response's body
REQUEST finish init function *url*
REQUEST elapsed time 3232.644053
REQUEST response end *url* 200
REQUEST end event *url*
REQUEST has body *url* 869964
REQUEST emitting complete *url*
App's THEN is called
App's FINALLY is called
```

Canceled request
```
REQUEST {}
REQUEST make request *url*
REQUEST onRequestResponse *url* 200
REQUEST reading response's body
REQUEST finish init function *url*
App calls CANCEL
App's FINALLY is called
REQUEST elapsed time 1997.353174
REQUEST response end *url* 200
REQUEST end event *url*
REQUEST aborted *url*
```

It would seem there is not completed emit in the canceled request. And, some of the events occur after FINALLY is called. I'm guessing all of this is as expected. I will have to spend some time looking into wireshark as I am not familiar but I will report back.

**Comment by analog-nico** [comment]
Alright. Yes, the events look good. The ordering is due to the asynchronous nature of how `bluebird` and `request` are stitched together here.

If you run your node server on your own development machine where you have sudo access then using Wireshark is really easy. Since it is monitoring all IP traffic the only challenge is to add a filter that filters out the noise.

**Comment by yourfavorite** [comment]
I'm wondering if there is a way for me to call agent.destroy() https://nodejs.org/api/http.html#http_agent_destroy while using the request-promise library. At the very least I'd like to test this. Though I'm not sure how to reference the agent in request-promise. Is it possible?

**Comment by analog-nico** [comment]
Yes, there is. FYI just to make sure: `request-promise` is based on `request`. So all you see in its README can be done with `request-promise` as well. In particular, there is [an option](https://github.com/request/request#requestoptions-callback) called `agent`. You can create and pass your own agent there and then easily call `.destroy()`. However, I don’t know the implications of doing this. So just use it for testing and if you need it for production really make sure you know that you are not breaking any `request` internals when calling `.destroy()`.

**Comment by yourfavorite** [comment]
So I've looked into this further. By using `const agent = new http.Agent()` I can then call `console.log(agent.sockets)` on an interval to see the proxy server connection get added to the sockets object. However this socket is removed from the sockets object before I ever call request-promise's `cancel()`. So I'm not sure that `agent.destroy()` is helping. Since this is the case I'm assuming that socket moves out of the agent once a connection to the request url is established. At that point, `cancel()` should take care of closing up all connections.

I think from here the best approach is to look into my proxy server and how it is handling requests. Thanks for all of the help Nico!

**Comment by analog-nico** [comment]
You are welcome buddy!
