### ISSUE TITLE
Setting user-agent when requesting

### ISSUE THREAD

**Issue by fabulousduck** [request/request-promise#209]
Currently when sending a request to a website, i get a `403, access denied` response. This could be avoided by setting the user agent to something like `Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36`.

I would like to know if this is possible and how as i have not been able to find it in the docs provided.

**Comment by analog-nico** [comment]
Yes, you can by using the [`User-Agent` header](https://github.com/request/request#custom-http-headers):

``` js
var options = {
  url: '...',
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36'
  }
};
```

FYI: `request-promise` is based on `request`. That means everything you read in [`request`’s README](https://github.com/request/request) is valid for `request-promise`, too.
