### ISSUE TITLE
How can I return the body?

### ISSUE THREAD

**Issue by VerHext** [request/request-promise#211]
I would like the body from a website from a function returnen. 
Example:

``` js
var ch = getChangelog('http://xxxxxxxx.com');
console.log(ch);


function getChangelog(url){
 return rp(url).then(function(body){
})
}
```

I hope you understand what I would like. Who knows how I can implement this, please with code example.

**Comment by analog-nico** [comment]
Yes, you can. But keep in mind that you are in the world of promises now. Everything is asynchronous and everything needs to be handled with promises.

``` js
function getChangelog(url) {
    return rp(url);
}

getChangelog('http://xxxxxxxx.com') // This doesn’t return the body itself. Instead a promise that will be resolved with the body
    .then(function (body) { // Use .then(...) because you are in the world of promises
        // Process the body here
    });
```

Makes sense?

**Comment by VerHext** [comment]
yes but can i set ths to a variable? 

e.g. 
``` js
var ch = getChangelog('http://xxxxxxxx.com') 
    .then(function (body) { 
        return body; // it is a objekt.
    });
```

**Comment by analog-nico** [comment]
`ch` is a promise in your case. At some other point in your code you can do:

``` js
ch.then(function (body) {
    // Process the body here
});
```

If you want `ch` to be the body object itself you need to use advanced techniques like ES6 generator functions or ES7 async/await.

**Comment by VerHext** [comment]
Ok thanks

**Comment by analog-nico** [comment]
You are welcome.
