### ISSUE TITLE
Crashing app with google oath2 token request

### ISSUE THREAD

**Issue by bliu886** [request/request-promise#215]
Using request-promise to get a google oauth2 token forcibly crashes the program with this error:

TypeError: First argument must be a string or Buffer
    at write_ (_http_outgoing.js:655:11)
    at ClientRequest.write (_http_outgoing.js:630:10)
    at Request.write (/Users/bliu12/Documents/stratus-server/node_modules/request/request.js:1514:27)
    at end (/Users/user/Documents/stratus-server/node_modules/request/request.js:552:18)
    at Immediate._onImmediate (/Users/user/Documents/stratus-server/node_modules/request/request.js:581:7)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

I am using Nodejs 8.3.0 on mac 10.12.6.

Here is a code snippit that fails:

	let Options = {
		method: 'POST',
		uri: 'https://www.googleapis.com/oauth2/v4/token',
		body: {
			code: googleAuthCode,
			client_id: clientId,
			client_secret: clientSecret,
			redirect_uri: "http://localhost:9000",
			grant_type: "authorization_code",
		},
	};

	try {
		console.log("before token request");
		let response = await rp(Options);

		// Does not get here
		console.log("google response:", response);
	} catch(error) {
		// Does not get here
		console.log("THERE WAS AN ERROR", error);
		return res.status(400).send("no");
	}

Not even this works:

	rp(Options)
		.then(function(response) {
			// Does not get here
			console.log("good:", response);
		}).catch(function(error) {
			// Does not get here
			console.log("error:", error);
		})

The program immediately crashes after the user logs in, and accepts using the google application. I can succeed in getting the oauth2 token from google using requests.

**Comment by analog-nico** [comment]
You are using `body` in your options. How do you intend to send this data?

1. As JSON. Then use:

``` diff
let Options = {
	method: 'POST',
	uri: 'https://www.googleapis.com/oauth2/v4/token',
	body: {
		code: googleAuthCode,
		client_id: clientId,
		client_secret: clientSecret,
		redirect_uri: "http://localhost:9000",
		grant_type: "authorization_code",
	},
+	json: true
};
```

2. As a querystring. Then use:

``` diff
let Options = {
	method: 'POST',
	uri: 'https://www.googleapis.com/oauth2/v4/token',
-	body: {
+	qs: {
		code: googleAuthCode,
		client_id: clientId,
		client_secret: clientSecret,
		redirect_uri: "http://localhost:9000",
		grant_type: "authorization_code",
	}
};
```

3. As form data. Then use:

``` diff
let Options = {
	method: 'POST',
	uri: 'https://www.googleapis.com/oauth2/v4/token',
-	body: {
+	form: {
		code: googleAuthCode,
		client_id: clientId,
		client_secret: clientSecret,
		redirect_uri: "http://localhost:9000",
		grant_type: "authorization_code",
	}
};
```

**Comment by bliu886** [comment]
Thanks! I needed to send the data as a querystring. I guess I didn't look at the documentation close enough.

In situations where the option parameters are malformed, could request-promise return an error message instead of crashing the entire program?

**Comment by analog-nico** [comment]
`request-promise` is built on top on `request` and this issue is one that needs to be fixed by `request`. Fortunately, [it already got reported](https://github.com/request/request/issues/2707).
