### ISSUE TITLE
passing "withCredentials: true" to server requests

### ISSUE THREAD

**Issue by NikhilNanjappa** [request/request-promise#218]
### Introduction
Let me start my saying, I love this package & use it a lot but ran into an issue lately. I am making a request **from my webapp** which is in another port & host to a REST API(which needs github login pre making this request). Firstly, when I make the below shown request via client/browser AJAX using the parameter `withCredentials: true`, I get the data from the server no problem!

### Issue
But when I try to replicate the same using node, I get `401: Authorization Required` error. This is obviously because I am not passing the required cookies/credentials via the node request. I have looked around a lot and tried passing the `sid` cookie via the request but with no success. I have also looked into your other similar answers of using `.jar()` or 'including a cookie' but have not been successful with this either(Maybe I'm not doing it right for my implementation)

Can you please help me out on how to achieve this without much complication.

```
  var asyncHttpPromise = require('request-promise');

  app.get('/', function(req, res) {

    var cookieText = 'sid='+req.cookies['connect.sid']; // I am not sure I'm doing this right?

    asyncHttpPromise({
      method: 'GET',
      uri: 'http://mydomain:3000/api/MyAsset',
      headers: {
        'User-Agent': 'Request-Promise',
        'Accept': 'application/json',
        'Cookie': cookieText
      }
    })
    .then(function (data) {
      //data
    })
    .catch(function (err) {
      //err
    });
  });
```

**Comment by analog-nico** [comment]
@NikhilNanjappa Hey! Did you check out the [cookie example](https://github.com/request/request-promise/blob/master/README.md#include-a-cookie) in the README? With `tough-cookie` it's much easier to set the cookie right.

**Comment by NikhilNanjappa** [comment]
@analog-nico Thanks for the quick reply. 

On deeper analysis, I've come to realize there seems to be an `access_token` which is supposed to be sent as part of the Cookie to the server. But `req.cookies` doesn't seem to have the `access_token`. Any help on this would be much appreciated.

PS: `access_token` is auto generated by LoopBack or OAuth

**Comment by analog-nico** [comment]
For the APIs I work with, the `access_token` always is a querystring. Use the `qs` parameter for that.

FYI, `request-promise` is based on `request`. Thus also have a look at the [`request` README](https://github.com/request/request). You can apply all its options to `request-promise` as well.

**Comment by NikhilNanjappa** [comment]
@analog-nico  Sorry, If I was not clear. I want to **fetch** the `access_token` from one response so I can use it & send it to another request. 

I understand for the second part `qs` is how you would send the `access_token` while making a request but for this I would need the value of `access_token` in the first place which I am trying to fetch/retrieve.

**Comment by analog-nico** [comment]
I sounds like your server will return a cookie with the `access_token` inside. The cookie jar will get updated at the end of the request. So look inside this jar and grab the `access_token` in the cookie you got.

**Comment by NikhilNanjappa** [comment]
Yes, `LoopBack` auto generates the tokens ..  so If I do something like this 

```
  app.get('/', function(req, res) {

    console.log(req.jar()); // <-This should contain the access_token ?    

    asyncHttpPromise({
      method: 'GET',
      ...
```
The result of the `.log` ideally should contain the `access_token` ?

**Comment by analog-nico** [comment]
Not `req.jar()`. This function generates a new cookie jar. Look into `cookiejar`.

But sorry buddy, I think we are now moving beyond the scope of an issue for this project. Please go through the docs first and let me know if you have some remaining doubts.

**Comment by NikhilNanjappa** [comment]
Sorry, I meant `cookiejar`. Forgot to edit. 

The above you mentioned returns `_jar: CookieJar { enableLooseMode: true, store: { idx: {} } } }`. Already tried it :-|

**Comment by analog-nico** [comment]
Sorry that I got off the radar. I hope you found the solution!
