### ISSUE TITLE
Not executing then or catch?

### ISSUE THREAD

**Issue by quinxy** [request/request-promise#219]
I'm confused and starting to question my sanity.  I execute the rp(options) and neither the then() nor the catch() are called.  I turned on debugging and see two debug entries one repeating the info about the request, then one saying it's making the request.  Am I missing something important?  Shouldn't then or catch always get called?  I put console.log statements everywhere and see no sign that the then/catch is executing.  I'm running this in Amazon Lambda, and presume I would see the entries in the console.log as I see all other log entries (I even added code to ping to an outside server from inside the then/catch to make sure they weren't executing and I just wasn't seeing the effects).  And don't think Lambda is timing out or anything.  If I change the URI to make it a bogus URI then the catch() is called as expected.  But if the URI is the one I want, nothing is called.

**Comment by analog-nico** [comment]
Well, this is so basic that there must be something wrong with your code. Could you post a code snippet for me to have a look?

**Comment by quinxy** [comment]
I am new to request-promise, so I was a little unclear on what way was best, so I tried a number of different ways of trying to pass in the data based on what I found here and there...  So here are some of the options I tried:

```
    var options = {
        method: 'POST',
        headers: {
                'content-type': 'application/x-www-form-urlencoded'
            },
        uri: 'https://foobar.com/auth/access_token',
        form: {
              client_id: 'foo',
              client_secret: 'bar',
              grant_type: 'password',
              scope: 'member',
              username: john,
              password: 'pass123',
          },
        json: true
    };

    var options = {
        method: 'POST',
        uri: 'https://foobar.com/auth/access_token',
        body: {
              client_id: 'foo',
              client_secret: 'bar',
              grant_type: 'password',
              scope: 'member',
              username: john,
              password: 'pass123',
          },
        json: true
    };

    var options = {
        method: 'POST',
        headers: {
                'content-type': 'application/x-www-form-urlencoded'
            },
        uri: 'https://foobar.com/auth/access_token',
        form: {
              client_id: 'foo',
              client_secret: 'bar',
              grant_type: 'password',
              scope: 'member',
              username: john,
              password: 'pass123',
          },
        json: true
    };

    var options = {
        method: 'POST',
        uri: 'https://foobar.com/auth/access_token',
        json: {
              client_id: 'foo',
              client_secret: 'bar',
              grant_type: 'password',
              scope: 'member',
              username: john,
              password: 'pass123',
          }
    };

```

When I test via the Postman app I post as an encoded form and that works fine.

As for the execution of rp() it's pretty normal:

```
console.log('about to post');
rp(options)
        .then(function (response) {
            // POST succeeded...
            console.log('Post succeeded: '+response.access_token);
        })
        .catch(function (err) {
            // POST failed...
            console.log('Post failed:'+err);
        });
console.log('after request to post');        
```
And as I say the code just never seems to execute the then() or catch() code.

Thanks again!  I hope this isn't the stupidest question you've been asked this week. ;)

**Comment by analog-nico** [comment]
No problem, buddy. Regarding the options have a look at [my first comment here](https://github.com/request/request-promise/issues/215). The 3rd variant is what you need to use. Did you properly encode your `uri`?

`then(...)` does not return the `response`. It only returns the `body`. If you want the full `response` use the [`resolveWithFullResponse` option](https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body). Other than that your `rp(...)...` call looks good.

Did you consider that your server may just not respond and for that reason `.then(...)` is not called?

**Comment by quinxy** [comment]
Hmm...

You asked if I properly encoded my uri.  It has nothing in it that needs url escaping, just letters, the forward slash, and an underscore.  Did you mean in case it had unusual characters in it?

As for the response, thanks for letting me know.  I did have the resolveWithFullResponse but forgot to include it in the code I posted (didn't realize the connection).

So I made the change, as reflected here, this is the literal code, but with the sensitive info changed.  and same result.

```
var options = {
		method: 'POST',
		uri: 'https://api.foobar.com/auth/access_token',
		form: {
		      client_id: 'foo',
		      client_secret: 'bar',
		      grant_type: 'password',
		      scope: 'something',
		      username: 3232323,
		      password: 'dsdsdsdsd'
		  },
		resolveWithFullResponse: true
	};

console.log('about to post');

rp(options)
	.then(function (response) {
		// POST succeeded...
		console.log('got token '+response.access_token);
        })
        .catch(function (err) {
		// POST failed...
		console.log('failed to get token');
        });
    
console.log('after');        
```
You asked about the server perhaps not responding.  It seems very unlikely for that to be the case because a) other parts of the code access the same REST API via request-promise (but via GET) and work fine, b) I can access it fine via Postman with all the same options.  I can't access the code for the REST API, so I can't prove it is responding or not, but all indications are that it should be.

**Comment by analog-nico** [comment]
I assume this issue is now outdated. But for everyone reading this, the next step after doing `console.log(...)` is to activate the debug mode to better understand what is going on. Here is how you can activate the debug mode: https://github.com/request/request-promise#debugging
