### ISSUE TITLE
Promise hangs even though it is resolved

### ISSUE THREAD

**Issue by tosbaha** [request/request-promise#220]
I am using request-promise module to check whether site is working with proxy or not. I am trying to find the proxies which is fast enough to answer in 5 seconds. Therefore I only add object if request doesn't timeout in 5 seconds.

For some proxies, even though promise resolves, node script hangs for a while. I can't find the reason of this delay. I see that it prints Done but it hangs. After 1 minute 10 seconds later, script exits. Is this hang due to my code, or operating system issue for open sockets etc?

```javascript
const rp =  require('request-promise');
const testProxies = [
    {
       "ipAddress": "80.241.219.83",
       "port": 3128,
    },
    {
        "ipAddress": "45.55.27.246",
        "port": 80
    },
    {
        "ipAddress": "144.217.197.71",
        "port": 8080,
    },
    {
        "ipAddress": "104.131.168.255",
        "port": 80,
    },
    ];

function CheckSites(sitesArray,site) {
    let ps = [];
    for (let i = 0; i < sitesArray.length; i++) {
        let proxy = sitesArray[i];

        let ops = {
            method: 'GET',
            resolveWithFullResponse: true,
            proxy: 'http://' + proxy.ipAddress + ':' + proxy.port,
            uri:site,
        };
        let resp =  rp.get(ops);
        ps.push(resp);
    }
    return Promise.all(ps.map(function (p) {
        p.time =  Date.now();
        return p
            .then(function (a) {
                return {'header':a.headers,'time':Date.now() - p.time};
            })
            .timeout(5000)
            .catch(function (e) {
                return {};
            })
    }))
}
CheckSites(testProxies,'https://www.example.com').then(function (object) {
    console.log('Done!');
    console.log(object);
}).catch(function (err) {
    console.log('Exception: ' + err);
});
```

**Comment by hamzaahmad** [comment]
use https://www.npmjs.com/package/proxy-agent with it

            method: 'GET',
            resolveWithFullResponse: true,
            agent: new ProxyNode('http://' + proxy.ipAddress + ':' + proxy.port),
            uri:site,
.... etc

**Comment by analog-nico** [comment]
@tosbaha You don’t need to implement your own timeout logic. Just use the `timeout` option for that. Since you did it this way, the requests that take longer are not actually aborted but still run in the background and for that reason your script doesn’t terminate.

**Comment by tosbaha** [comment]
@analog-nico I was using my own timeout logic because, request `timeout` doesn't work if there is proxy involved in the equation. Timeout is ignored for proxy connection. I think there was a PR for proxy timeout but AFAIK, it was not merged.

**Comment by analog-nico** [comment]
I see. Good to know @tosbaha ! I don’t know the status of `request` but maybe they have added it by now. In any way, that would be something that needs to be taken care of on `request`‘s side.
