### ISSUE TITLE
Use with Angular.js - clashing Promise implementations

### ISSUE THREAD

**Issue by seanoshea** [request/request-promise#227]
I'm trying to use the `4.2.2` version of `request-promise` in an Angular 4 app. I've developed an in-house networking library for making API calls which is based off `request-promise`. I'm distributing my library as an internal node module which allows me to load it like:
```
import my_lib from 'my_lib';
```
My `package.json` looks like:
```
"dependencies": {
    "request": "^2.81.0",
    "request-promise": "^4.2.1"
  }
```
 but I get the following exception when I try to use it:
```
_Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
```
This might be more of a feature request rather than a bug, but is there any way to have `request-promise` check for `window.Promise` before trying to load the `Bluebird` polyfill?

**Comment by seanoshea** [comment]
Wondering if https://github.com/angular/zone.js/pull/899 will take care of this?

**Comment by analog-nico** [comment]
Hi @seanoshea , `bluebird` within `request-promise` does not act as a polyfill. That means it leaves the global `Promise` untouched. Your error must have been caused by something else.

Btw, if you prefer to use a different promise implementation even for `request-promise` itself, you may look into `request-promise-native` and `request-promise-any`.

**Comment by seanoshea** [comment]
https://github.com/angular/zone.js/pull/899 did not take care of this. Getting:
```
zone.js:634 Uncaught TypeError: NativePromise.resolve is not a function
```
now.
