### ISSUE TITLE
Lodash is really necessary?

### ISSUE THREAD

**Issue by msfidelis** [request/request-promise#228]
I use `request-promise` library to create communication between a lot of microservices using AWS Lambda. Using `request-promise`, i need to increment 5 MB in my package deploy because rp uses lodash. It's really necessary? 

![Lodash](https://i.imgur.com/Se3y9tW.png)

**Comment by analog-nico** [comment]
Hi @msfidelis , there is a [pull request](https://github.com/request/promise-core/pull/7) for the core library that I will merge shortly. It will replace the whole `lodash` library with just the functions that are needed. Stay tuned!

**Comment by VuBui83** [comment]
Hi @analog-nico, it has been a few months since your last comment, just wonder if you've found the time to merge the PR. Thanks for the great work!

**Comment by analog-nico** [comment]
Nowadays, `request-promise` uses `request-promise-core` which depends on the whole `lodash` library but requires each function specifically. That means that if you use a module bundler like Webpack then you will get the smallest possible size for your code base.

**Comment by xXxrAinZyian** [comment]
Ok

**Comment by xXxrAinZyian** [comment]
Cool

**Comment by xXxrAinZyian** [comment]
Ok

**Comment by xXxrAinZyian** [comment]
Done
