### ISSUE TITLE
What is `os`?

### ISSUE THREAD

**Issue by kirakik** [request/request-promise#233]
On line 19 of `rp.js`, it states `var EOL = require('os').EOL;`
I am working on a react native application which has a dependency that depends on `request-promise`, and for some reason I get an exception at this line saying `Unable to resolve module `os` from `node_modules/request-promise/lib/rp.js`

Any insight would be very appreciated!

Thank you.

**Comment by analog-nico** [comment]
Hi @kirakik , I assume that you package your react app to be executed in the browser, right? `request-promise` is build for node.js. If you want to use it in the browser you need to polyfill all node.js dependencies. `os` is one of them.

I could suggest some alternative solutions but it sounds like the `request-promise` dependency is not in your hands. So polyfilling is the only option.
