### ISSUE TITLE
send the response to client sents empty object?

### ISSUE THREAD

**Issue by emjimadhu** [request/request-promise#234]
so this is my structure now.

`calculate (req, res) {

    let postData = {

      method: 'POST',

      uri: 'http://localhost:3000/cars',

      body: req.body,

      json: true

    }

    apiCall(postData)

      .then((res) => {

        res.status(200).send(res)

      })

      .catch((err) => {

        res.send(err)

      })

  }
`

so in my structure i get the response when console log. but when i try to send, it sends empty object.

what is wrong in here?

**Comment by analog-nico** [comment]
All looks good to me. Did you inspect `res` which you get from the api call?

**Comment by emjimadhu** [comment]
@analog-nico inspect in the sense? I receive the res from apicall.. I can log it in console.. but only problem is I can't send the res.. may be this is dumb question.. I'm pretty much confused here..

Thanks..

**Comment by analog-nico** [comment]
Yes, logging it to the console or using the debugger. It sounds like you have this situation:

``` js
apiCall(postData)
  .then((res) => {
    console.dir(res) // --> Logs the data as expected
    res.status(200).send(res)
  })
```

This means the issue is with your `express` call and not with `request-promise`.

Oh, I spotted it: Silly mistake in the end. You have a naming conflict. You use `res` twice. Rename it like so:

``` js
apiCall(postData)
  .then((res2) => {
    res.status(200).send(res2) // See the difference?
  })
```
