### ISSUE TITLE
Either the then or catch is not called if the promise is called from other promise resolve

### ISSUE THREAD

**Issue by zer09** [request/request-promise#240]
I am not sure if it is the same with #219 , but it could be we got this on different process.

On my concern, The Promise will execute successfully when not called in inside from other promises.
.e.g.

``` 
function thePromiseInQuestion() {
    console.log('This should be called.');
    rp({...}).then(b => {
        console.log('Success');
    }).catch(e => {
        console.log(e);
    });
   console.log('done calling thePromiseInQuestion');
}

function func1() {
    thePromiseInQuestion();
}

function func2() {
    Promise.all(...).then(data => {
        console.log('Promise all done.');
        thePromiseInQuestion();
        console.log('Promise all end.);
    }).catch(e => {
        console.log(e)
    });
}
```

Calling the ```func1``` got the expected result:
```
This should be called
Success
done calling thePromiseInQuestion
```

But when ```func2``` is called either of the ```then``` or ```catch``` of ```thePromiseInQuestion``` is not called. It will just look like this.
```
Promise all done.
This should be called.
done calling thePromiseInQuestion
Promise all end.
```
There is no ```Success``` or ```Error``` message.
I alse added ```resolveWithFullResponse: true``` but rendered the same result.

So I tried to compare the promise object between  ```func1``` and ```func2``` by logging the object ```console.log(rp(...));```.

And what I observe is that, when the ```thePromiseInQuestion``` is called by ```func2``` the ```response``` and ```responseContent``` property is missing.

Please give a hint how should I fix this.
Thanks.

**Comment by zer09** [comment]
And it look like, the expressjs server doesn't the receive  ```GET``` request.

**Comment by analog-nico** [comment]
Hi @zer09 , you need to take care of the proper handling of promises in general. Here is what you need:

``` diff
function thePromiseInQuestion() {
    console.log('This should be called.');
-   rp({...}).then(b => {
+   return rp({...}).then(b => {
        console.log('Success');
    }).catch(e => {
        console.log(e);
-   })
+   }).finally(() => {
+       console.log('done calling thePromiseInQuestion');
+   });
-   console.log('done calling thePromiseInQuestion');
}

function func1() {
-   thePromiseInQuestion();
+   return thePromiseInQuestion();
}

function func2() {
    Promise.all(...).then(data => {
        console.log('Promise all done.');
-       thePromiseInQuestion();
+       return thePromiseInQuestion();
+   }).then(b => {
        console.log('Promise all end.);
    }).catch(e => {
        console.log(e)
    });
}
```

**Comment by zer09** [comment]
Thanks for the advice @analog-nico .

I did your advise, sorry but it doesn't fix the issue, actually the code above is just for demonstration purpose only, and I don't need to return the promise because I just need to consume the data on the ```then``` block of the promise.

**Comment by ckyleda** [comment]
Was this ever resolved?
I have exactly the same issue - indication of a deeper bug within request-promise perhaps?

**Comment by zer09** [comment]
@ckyleda  nope, probably the origin of the issue from the ```request```, btw what OS are you in when you experience it?
I already filled an  issue there request/request#2851

**Comment by ckyleda** [comment]
@zer09 Using Antergos.
I also tested this using a pure request call - whose callback also didn't trigger, so I suspect you are right with there being an issue with request.

**Comment by ckyleda** [comment]
@analog-nico Can we reopen this? 

It's a serious issue - and renders request unusable if it just refuses to work on certain systems.
