### ISSUE TITLE
npm test failed with error Bad response:422 {"message":"Couldn't find a repository matching this job.","error":true}

### ISSUE THREAD

**Issue by snehlatamohite** [request/request-promise#248]
We have tried to build the package from source using below steps and npm build was successful but  
npm test failed with error Bad response:422 {"message":"Couldn't find a repository matching this job.","error":true}

Steps - 

apt-get update
apt-get install -y  npm git wget
git clone --depth=50 https://github.com/request/request-promise.git request/request-promise
cd request/request-promise/
git fetch origin +refs/pull/243/merge
git checkout -qf FETCH_HEAD
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh| sh
source ~/.nvm/nvm.sh
export V_REQUEST=2.76.0
npm install request@$V_REQUEST
npm install tough-cookie
npm install gulp-coveralls
npm install stable
npm use stable
npm install && npm test

**Comment by analog-nico** [comment]
I think this is an issue with the linux package. Feel free to reopen if you still have issues.
