### ISSUE TITLE
how to transform image type's response?

### ISSUE THREAD

**Issue by ruanjiayou** [request/request-promise#250]
rp can attach a image,but how to down a image?
Chinese: rp能上传文件,但如何下载图片?

**Comment by analog-nico** [comment]
To download images I recommend that you use `request` with streams like explained here: https://stackoverflow.com/questions/12740659/downloading-images-with-node-js

You can of course use `request-promise` to get the full response and save the data to as file as well but this approach has the disadvantage that the full file data is in memory at one point. So if you download many and / or big files then this has a bad impact on your memory footprint.

Btw, you can use `request-promise` and `request` side by side. So use `request` for the downloads and `request-promise` for everything else.
