### ISSUE TITLE
Documentation: how to specify certificate and key for https

### ISSUE THREAD

**Issue by ajmas** [request/request-promise#251]
Could you add to the documentation how to specify the ssl certificate and key when using an https connection with a self signed certificate?

I had hoped that you would use the same parameters as the following example, but 'cert' and 'key' seem to be ignored: https://stackoverflow.com/questions/35478215/how-to-do-https-get-with-client-certificate-in-node

**Comment by TAVkiev** [comment]
Any news ?

**Comment by kyle-wrenn** [comment]
I was able to follow the same pattern described in the [request documentation](https://github.com/request/request#tlsssl-protocol)

```
var fs = require('fs')
    , path = require('path')
    , certFile = path.resolve(__dirname, 'ssl/client.crt')
    , keyFile = path.resolve(__dirname, 'ssl/client.key')
    , caFile = path.resolve(__dirname, 'ssl/ca.cert.pem')
    , request = require('request');

var options = {
    url: 'https://api.some-server.com/',
    cert: fs.readFileSync(certFile),
    key: fs.readFileSync(keyFile),
    passphrase: 'password',
    ca: fs.readFileSync(caFile)
};
```

**Comment by DanBurkhardt** [comment]
> I was able to follow the same pattern described in the [request documentation](https://github.com/request/request#tlsssl-protocol)
> 
> ```
> var fs = require('fs')
>     , path = require('path')
>     , certFile = path.resolve(__dirname, 'ssl/client.crt')
>     , keyFile = path.resolve(__dirname, 'ssl/client.key')
>     , caFile = path.resolve(__dirname, 'ssl/ca.cert.pem')
>     , request = require('request');
> 
> var options = {
>     url: 'https://api.some-server.com/',
>     cert: fs.readFileSync(certFile),
>     key: fs.readFileSync(keyFile),
>     passphrase: 'password',
>     ca: fs.readFileSync(caFile)
> };
> ```

Do you have an example of the implementation? Still seems to be ignoring the certificates for me in this framework

**Comment by analog-nico** [comment]
Yes, the approach from the request documentation as you see above is the solution. It works exactly like that for `request-promise`, too.

@DanBurkhardt `url` and `uri` are interchangeable parameters. Just use one of the two. Make sure that your url begins with `https://` with an “s”.

**Comment by DanBurkhardt** [comment]
Thanks for the follow-up! This resolved it for me.

**Comment by analog-nico** [comment]
Excellent! Happy coding @DanBurkhardt . :)

**Comment by guptapranay** [comment]
This doesn't work for me. I am using below code and i just get some java object with exit code 0. Kindly help me to solve this issue.
`
let request = require('request-promise');
let crtFile = fs.readFileSync('someFilePath.cer');
let pemFile = fs.readFileSync('someFilePath.pem');

let options = {
  method: 'GET'
  uri: 'http://localhost:8888/getDetails'
  json: true,
  agentOptions: {
    cert: fs.readFileSync(crtFile),
    key: fs.readFileSync(pemFile),
    passphrase: 'London1!'
    rejectUnauthorized: false
  }
}
let response = request(options).then(function(body) {
     return body;
});
console.log(response);`

Response received:
`Promise {
_bitField: 0,
_fulfillmentHandler0: undefined,
_rejectionHandler0: undefined,
_promise0: undefined,
_receiver0: undefined,
_cancellationParent: 
Promise {
_bitField: 1,
_fulfillmentHandler0: [Function],
_rejectionHandler0: undefined,
_promise0: [Circular],
_receiver0: undefined,
_onCancelField: [Function],
_branchesRemainingToCancel: 1 } }
undefined

Process finished with exit code 0`

**Comment by ajmas** [comment]
@guptapranay your problem is that you aren't using promises properly, since 'response' at this point will be the promise and not the result of the promise. It should be:

```js
let response = request(options).then(function(body) {
     return body;
}).then(function(body) {
  // handle the body
}.catch(function(error) {
  console.log(err);
}
```
Though, if you are using a recent version of NodeJS, then my personal preference is to migrate to async/await:

```js
try {
  const response = await request(options);
  const body = response.body;
  // handle the body
} catch (error) {
   console.log(error);
}
```

**Comment by guptapranay** [comment]
Thanks so much @ajmas . It worked.

**Comment by guptapranay** [comment]
@ajmas,
I am unable to assign response to global variable.
Is there a way we can store response in global variable so that we can use it anywhere?
