### ISSUE TITLE
RequestError: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by ckurban** [request/request-promise#255]
Hi 

I have request promise version 2.83.0
When I make a api call to the backend via **request-promise** then I am getting below written timeout error BUT when I make same call via POSTMAN then it works fine. Seems to be error is down to the request-promise.

{ RequestError: Error: connect ETIMEDOUT 54.229.253.90:443
    at new RequestError (/Users/xxx/dev/yyyy/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/xxx/dev/yyyy/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/xxx/dev/yyyy/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/xxx/dev/yyyy/node_modules/request/request.js:186:22)
    at Request.emit (events.js:127:13)
    at Request.emit (domain.js:421:20)
    at Request.onRequestError (/Users/xxx/dev/yyyy/node_modules/request/request.js:878:8)
    at ClientRequest.emit (events.js:132:15)
    at ClientRequest.emit (domain.js:421:20)
    at TLSSocket.socketErrorListener (_http_client.js:394:9)
    at TLSSocket.emit (events.js:127:13)
    at TLSSocket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)

**Comment by munnamathew** [comment]
I am facing same issue as well. Any one got any resolution ideas?

**Comment by cyborg29** [comment]
Here's a workaround.
You have to add manually your proxy specification as part of reqOpts in the request.js file (npm\node_modules\@vue\cli\lib\util).

`const request = require('request-promise-native')

module.exports = {
  async get (uri) {
    const reqOpts = {
      method: 'GET',
      resolveWithFullResponse: true,
      json: true,
      uri,
      proxy: 'http://<your.proxy.info>:8080'    }

    return request(reqOpts)
  }
}
`

**Comment by MamidiVasavi** [comment]
Hi,

We are facing this issue intermittently, can someone help with the resolution of this issue.

**Comment by analog-nico** [comment]
This is an issue on the network level and has most likely to do with your proxy configuration. Using the `proxy` like @cyborg29 shows above is indeed the solution to that. But since this affects all your requests, you may make your life easier by using the `.defaults(...)` function:

``` js
var rp = require('request-promise')

var rpWithProxy = rp.defaults({
    proxy: 'http://<your.proxy.info>:8080'
})

module.exports = rpWithProxy
```

I wrote the snippet as a node.js module so that you can use it everywhere in your code instead of `request-promise` directly. This way you have a central place where you can configure default options for all your requests.

**Comment by joshden** [comment]
I'm facing this issue as well. I'm not using a proxy (though the server is a load balancer). So I don't see how setting the `proxy` option is a resolution for this issue. I don't even have a value I would set it to. Thanks.

**Comment by fandujar** [comment]
@ckurban, @joshden  I got this error recently when requesting to a server using https (port 443) that didn't have a valid certificate.

You can confirm this behavior by editing your /etc/hosts (or hosts on Windows) adding a record with IP address and the host Common Name (that you can get check inside certificate)

**Comment by Zerone-MS** [comment]
> I'm facing this issue as well. I'm not using a proxy (though the server is a load balancer) nor did the OP mention anything about a proxy. So I don't see how setting the `proxy` option is a resolution for this issue. I don't even have a value I would set it to. Thanks.

How did you fixed it ?

**Comment by somahargitai** [comment]
Any update on this? I have the same error. I scrape several links on a website, then download them too. About 40 out of 900 downloads fails with this error. I think I timply have to modify time limit, but I don't know where.

**Comment by analog-nico** [comment]
@somahargitai You can find all options in the [`request` docs](https://github.com/request/request#requestoptions-callback) on which `request-promise` is based on. There is a `timeout` option.

**Comment by rofc** [comment]
Same issue here, any workaround?
