### ISSUE TITLE
Bearer Token not working due to old Request Version 2.34

### ISSUE THREAD

**Issue by anouarkacem** [request/request-promise#256]
Error: auth() received invalid user or password

I think this is because of request version is 2.34 and it should be at least 2.35/2.36 for bearer token

**Comment by frnk01** [comment]
I have this exact same issue. Hope it's resolved soon.

**Comment by analog-nico** [comment]
`request-promise` only requires `request@2.34` as the oldest supported version. Feel free to install a newer version.
