### ISSUE TITLE
returning html page that is not fully loaded

### ISSUE THREAD

**Issue by saalmaan** [request/request-promise#259]
Hello, 

I am trying to make a request to a page (https://azimo.com/en/send-money-to-australia) but HTML data returned is not fully loaded. This website is client-side rendered so the request is missing rendered data.

```
const rp = require('request-promise');
const cheerio = require ('cheerio');

let request = {
  uri : 'https://azimo.com/en/send-money-to-australia',
  transform : body => cheerio.load(body)
}

rp(request)
  .then(($) => {
    const rate = $("#currentRate").val();
    console.log(rate);
})
```

How do I wait for page to fully render and load and then get the data?

PS. using nightmare I can get the data I want

**Comment by esraamostafa94** [comment]
I have the same problem, did you find a solution??

**Comment by analog-nico** [comment]
As you say, the missing part is the client-side rendered data. And it’s not a matter of waiting. Just using `request-promise` + `cheerio` just doesn’t do this job. The approach you’d need to take is to use a headless browser which does all the rendering for you and then get the page source from that browser.
