### ISSUE TITLE
Possibly unhandled StatusCodeError

### ISSUE THREAD

**Issue by woky** [request/request-promise#263]
The following code

	(async () => {
		try {
			const response = rp('http://example.com/nonexistent');
		}
		catch (e) {
			if (e.statusCode === 404)
				doA();
			else
				doB();
		}
	})();

spews error messages to stderr when it encounters HTTP 404 response. The messages begin with

    Possibly unhandled StatusCodeError: 404

Clearly, the `StatusCodeError` is handled.

#47 is related, but there it was deemed _good design choice_.

**Comment by kukawski** [comment]
In the code you've posted, you're missing `await` in front of the `rp()` call.

**Comment by analog-nico** [comment]
Yep, exactly. Add the `await` and you are good.
