### ISSUE TITLE
Is it possible to parse IncomingMessage params?

### ISSUE THREAD

**Issue by djrolleyes** [request/request-promise#266]
Anytime I try to get response referer or any another properties of IncomingMessage it returns undefined. I just trying to understand wich promise of promises array corresponds to array of my requests.

Well, maybe I can pass variable to request to get it into the responce? Is there any correct pattern to get it?

**Comment by analog-nico** [comment]
Yes, you can. Use the `resolveWithFullResponse: true` option for it. Here is an example in which `response` is the `IncomingMessage` object: https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body
