### ISSUE TITLE
Is timeout handled? .then() or .catch() none of them gets executed if response takes more than ~120 seconds

### ISSUE THREAD

**Issue by shubhamcronj** [request/request-promise#269]
`var rp = require('request-promise');
var config = require('../config');
var baseURI = config.urls.baseURL;

module.exports = {
	requestClient : function(method, uri, body, isJSON){
		var options = {
		    method: method,
		    uri: baseURI + uri,
		    body: body,
		    json: isJSON // Automatically stringifies the body to JSON 
		};
		console.log(options);
		return new Promise((resolve, reject) => {
			return rp(options)
				.then(data => {
					return resolve(data);
				})
				.catch(err => {
					return reject(err);
				})
		})
	}
}
`

**Comment by analog-nico** [comment]
You can use the `timeout` parameter for this. For details look at the parameters of the `request` library on which `request-promise` is based: https://github.com/request/request#requestoptions-callback
