### ISSUE TITLE
Query string size limit

### ISSUE THREAD

**Issue by grath90** [request/request-promise#272]
Is there a limit on how long a query string can be in a request? If there is, what is the best option to compress it?

**Comment by analog-nico** [comment]
Query strings are part of the url that your request is connecting to. So the official standards apply. The actual limit is defined by the server you are connecting to. Besides that, the query string is just text. Within the limits of allowed characters for query strings you can put there anything you want. Feel free to use some sort of text based compression even.

That said, if you want to transfer larger amounts of data, consider doing POST requests with the payload in the body.
