### ISSUE TITLE
Error promise.all 404 randomly

### ISSUE THREAD

**Issue by JamilOmar** [request/request-promise#281]
I am performing a promise.all to perform parallels tasks, sometimes unexpectedly a random 404 error appears even with the correct http address

**Comment by analog-nico** [comment]
If you get a 404 error as a regular `StatusCodeError` then most likely all went as expected on your side. I recommend that you debug your server or if you don’t have access to it, monitor the HTTP traffic using WireShark for example. This will give you more insight into why the server sends a 404.
