### ISSUE TITLE
How do I pass query param in request URL

### ISSUE THREAD

**Issue by Suvin1987** [request/request-promise#282]
Hi, 

I want to pass query param in my request URL. How can I do it? 
for e.g, 
my request url is http://test.com/{userID}/fetchdatausinguserID

The {userID} value would be passed by me

**Comment by analog-nico** [comment]
Btw, the cleaner solution than concatenation is to use the `qs` parameter. Here is an example: https://github.com/request/request-promise#get-something-from-a-json-rest-api

The `qs` parameter does the job for you to properly escape whatever you put into it.
