### ISSUE TITLE
PUT request sending empty body even though I'm setting it

### ISSUE THREAD

**Issue by biot023** [request/request-promise#284]
Hi -- I'm having an issue where I'm setting the body of a PUT request but the body isn't being sent with the request. The code looks like this:

```
async saveData(itemId, customisations) {              
  const options = {                                   
    uri: this.endpoints.itemCustomisationData(itemId),
    method: 'PUT',                                    
    headers: this.headers,                            
    body: { customisations: customisations },         
    json: true,                                       
  };                                                  
  console.log(JSON.stringify(options));               
  const req = rp(options);                            
  console.log(req);                                   
  return req.json();                                                                                        
}                                                     
```

When I inspect the options object in the console, the body is clearly set:

`{"uri":"http://app.localhost/api/v1/current-user/item-customisations/5","method":"PUT","headers":{"X-App-User-ID":4,"X-App-User-Token":"8a257c17df4b3b3f153a7516af76722993a2491f"},"body":{"customisations":[{"index":0,"type":"required_text","name":"Your name","label":"Your name here"}]},"json":true}`

However, when I inspect the request object in the console, its body is `undefined`.

I have intercepted the call using [Charles](https://www.charlesproxy.com/) as a proxy, and when I inspect the body of the call there, it has 0 bytes.

Also, the request does hit my local backend server, but when I print the raw post data, it is just empty.

So I'm pretty certain that the issue is that I'm doing something wrong with `request-promise`.

I've tried explicitly `JSON.stringify()`-ing the data and explicitly setting the `Content-Type` header to `application/json`, but all to no avail.

Can anybody advise me on where I'm going wrong, here?

Thanks for any and all advice,
   Doug.

**Comment by biot023** [comment]
Can anybody offer me any advice on this?
I've tried everything I can think of, including:

* Changing the `PUT` to a `POST` in the front end and backend -- exact same error
* Changing the backend to return a 404 to make sure nothing is wrong there -- it worked as expected

Could anybody at least tell me that I've not done anything they can see wrong?
99.99% of the time these issues are something I've missed but I've gone through everything I can think of and am still drawing a blank.

Is there a request library similar to `request-promise` that I could try to drop in to make sure it's not a library issue? Like I say, I seriously doubt that it is but I've exhausted everything I can think of to try to fix this.

Thanks again for any and all advice you can offer,
   Doug.

**Comment by rayk47** [comment]
This is just some off the cuff suggestions so it may not be correct as I have not tried to run my theories.

1. Rename your variable 
`customisations: customisations`
Won't this pull in and use your variable twice?

2. Do you need to wrap the value with '' ?

**Comment by Bendihossan** [comment]
@biot023 I've also been able to reproduce this issue. I found the same symptoms after upgrading from Node 8.11 to Node 8.15. Somewhere between those two versions a breaking change appears to have been introduced. Rolling back to Node 8.11 resolved it for now but I've begun migrating to Node 10 anyway.

**Comment by analog-nico** [comment]
@biot023 I assume you already dealt with it. Anyways, better late than never. Your `req.json()` line is most likely the issue. Instead you should use a promise function like `.then(...)` to work with the promise. No need for `.json()`. Here is the example to post data which is the same for PUT: https://github.com/request/request-promise#post-data-to-a-json-rest-api

Thanks for mentioning the node version issue @Bendihossan . Anyone who finds this issue, try upgrading node.
