### ISSUE TITLE
POST request hangs up / seems to run forever 

### ISSUE THREAD

**Issue by Xavi55** [request/request-promise#290]
Hello, I'm having trouble sending a post request to gather the html from a website.
I'm setting up the request like so,

```
var options = 
        { 
            method: 'POST',
            url: 'https://www.nasdaq.com/symbol/ge/historical',
            headers: 
            { 'postman-token': '83993654-a2f6-b811-2bad-7e56ac6b6865',
                'cache-control': 'no-cache',
                'content-type': 'text/plain' },
            body:'5d|false|ge',
            json:false
        };
```

then using,

```
 request(options)
        .then(res => 
            console.log(res)
        )
        .catch(err => 
            console.log(err)
        );
```

I tested this with [https://httpbin.org/post](url) to see what it looks like and to verify that it goes through.

I used Google's Postman and I can get the html I want, but now it seems I'm having trouble re-creating the request it in NodeJS.

Please help me with this,
-Kevin G.

**Comment by Xavi55** [comment]
Thanks for the suggestion, but I've had no luck with it.
I thought it was a user-agent issue, I assumed the site has some type of security or something, so I've tried this now: 
```
var options = 
        { 
            method: 'POST',
            url: 'https://www.nasdaq.com/symbol/ge/historical',
            headers: 
            { 'postman-token': '83993654-a2f6-b811-2bad-7e56ac6b6865',
                'cache-control': 'no-cache',
                'content-type': 'text/plain' },
            body:'5d|false|ge',
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
            json:false,
            timeout:2500,
            debug:true
        };

request(options)
        .then(res => 
            console.log(res)
        )
        .catch(err => 
            console.log(err)
        );
```
I suppose what I basically want to do is to get a different page from the same website. I'm sending the `{body:'5d|false|ge'}`, as my Chrome browser did the same, but it still didn't work despite my efforts.
Have you tried running it?

**Comment by shirshak55** [comment]
are u doing this on other site. then make sure all header are passed.
remove postman header check cookie and gzip

**Comment by analog-nico** [comment]
There are different types of timeouts on the code level as well as the os level. Having the `timeout` parameter is a good start and aborts the request in some situations. In other situations the timeouts of the os will fire. Since those are much longer usually just run your request and wait a few minutes. You should then get an error which you could look into.

**Comment by analog-nico** [comment]
Feel free to reopen @Xavi55 if you still need a solution.
