### ISSUE TITLE
Get request object

### ISSUE THREAD

**Issue by xxluke** [request/request-promise#293]
Is it possible to get the actual request object, like I would get if I used `http.request`?

I want to use it for debugging reasons, I'm trying to get the curl command by using the [request-as-curl](https://www.npmjs.com/package/request-as-curl) or [request-to-curl](https://www.npmjs.com/package/request-to-curl) package.

**Comment by analog-nico** [comment]
Yes. Use the `resolveWithFullResponse: true` parameter to get the full response object (`IncomingMessage`) and then use `response.req` which is the request object (`ClientRequest`). Here is an example of how to use the `resolveWithFullResponse` parameter: https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body
