### ISSUE TITLE
How to use API path parameter in request/request-promise libraries?

### ISSUE THREAD

**Issue by jjayaraman** [request/request-promise#295]
How to use API path parameter in request/request-promise libraries?

`const express = require('express');
const router = express.Router();
const rp = require('request-promise');

router.post('employee/:id', (req, res) => {
    const id = req.params.id; // I dont know how to use this in request library
    handleRequest(req, res);
})

function handleRequest(req, res) {

  const id = req.params.id; // I dont know how to use this in request library options? 

  var options = {
    method: req.method,
    uri: 'http://api.anotherhost.com/external/'+ req.path,
    body: req.body,
    qs: req.query,
    json: true
  };

  rp(options)
    .then((success) => res.send(success))
    .catch((err) => res.status(err.statusCode).send(err.message));
}`

Question:  https://stackoverflow.com/questions/53706880/how-to-use-api-path-param-in-npm-request-request-promise-libraries

**Comment by analog-nico** [comment]
Your goal is to have the path parameter value appended to your `options.uri` string, right?

This is rather a question for `express` but anyways. First, get the path from `req` like this: https://stackoverflow.com/questions/42735645/express-js-get-url-path-without-any-additional-parameters
And then it’s just a matter of string concatenation for your `options.uri` parameter.

I hope this helps!
