### ISSUE TITLE
Couldn't get it work with nock

### ISSUE THREAD

**Issue by ben-mobify** [request/request-promise#296]
I'm having issues with getting request-promise work with nock. It keeps saying "Cannot read property then of undefined". Any help is appreciated. 
```
const requestPromise  = require('request-promise')
const nock = require('nock')
test('random test', () => {
    const test = nock('https://www.test.com')
    .get('/target')
    .reply(200, 'random message')
    const requestOptions = {
        uri: 'https://www.test.com/target',
        method: 'GET'
    }
    requestPromise(requestOptions) // it keeps saying couldn't read "then" of undefined on this line
    .then(() => {
        if (test.isDone()) {
            console.log('pass!!!')
        }
    }).catch((error) => console.log(error))
})
```

**Comment by ben-mobify** [comment]
I think the issue has nothing to do with nock, the real issue is request promise does not work well with jest. [Check this](https://github.com/request/request-promise/issues/247)

**Comment by analog-nico** [comment]
@petrgazarov submitted a piece of documentation that explains how to use nock: https://github.com/request/request-promise/pull/232/files Does this help maybe? If not, do you have more details of what goes wrong?

**Comment by analog-nico** [comment]
Feel free to reopen @ben-mobify if you want to follow up on this.
