### ISSUE TITLE
Not able to authenticate SAML/SSO sites

### ISSUE THREAD

**Issue by Kunal912** [request/request-promise#297]
Hi Support,

I am trying to scrap site that uses saml/sso authentication.Everytime i try to make request withe server it says access denied but wirks fine with sites don't have saml/sso auth.

Please suggest the solution.

Thanks

**Comment by analog-nico** [comment]
The key to authenticate for SAML properly is having the right cookie, right?

FYI, `request-promise` is based on `request` and thus all `request` options can be used for `request-promise`, too. For starters, have a look at what [options `request` provides](https://github.com/request/request#requestoptions-callback).
