### ISSUE TITLE
rejected promise not handled within 1 second

### ISSUE THREAD

**Issue by Rolodo** [request/request-promise#298]
I am using the lib in a vscode extension.
I'm doing something like that :

```javascript
import * as rp from 'request-promise';
//[...]
rp({method: "GET",
		uri:  <URL>,
		headers: {
			"Authorization": <OPTIONS.AUTENTIFICATION_TOKEN>,
			"User-Agent": <OPTIONS.USER_AGENT>,
			"Accept": <OPTIONS.CONTENT_TYPE>,
			"Content-Type": <OPTIONS.CONTENT_TYPE>,
		},
		body: {},
		json: true
	}).then(r => {
            //log
        }).catch(e => {
            //log
});
//[...]
```

so if I call it 3 time.
- 1st time without error.
-- It goes well
- 2nd time with an error in the uri (wrong link or wrong target)
-- seems to go well go in the catch and log correctly
- 3rd and after with or without error
-- doesn't get to the then or catch only log : rejected promise not handled within 1 second.

I've never created an extension for vscode... if someone can confirm if this is a bug from the lib or from vscode.

Thanks!

**Comment by M4DM0NK3Y** [comment]
Did you manage to solve this? I am having the same issue!

**Comment by Rolodo** [comment]
For me it seems that my logic was not good folloing callback ...
I solved this be changing the order I was doing my call
try adding async for all your call instead of doing the .then
speculating ... (if this is a real bug?? could it be that the current request instance is not closed before the other are called ?)
