### ISSUE TITLE
Get full response on rejection with Promise.all

### ISSUE THREAD

**Issue by fcarriedos** [request/request-promise#301]
Hello there,

I am using the client with Promise.all, forming an array of promises.

Each of the requests can succeed or fail, but if one or more fails, I am trying to avoid losing the successful ones. For that I massaged a bit my code around Promise.all:

```
Promise.all(pagesRequestPromiseArray)
		.catch(errorResponse => {
			console.log('getOwnedPagesData(): received error ' + errorResponse);
			return pagesRequestPromiseArray;
		})
		.then(successResponses => {
			console.log('Success size ' + successResponses.length + ' - ' + JSON.stringify(successResponses));
			console.log('Detecting errors: ');
			successResponses.forEach((response) => {
				// console.log('getOwnedPagesData(): received response ' + response);
				console.log('Error? ' + response instanceof Error);
				console.log('Body: ' + JSON.stringify(response));
			});
		});
```

Like that I am able to get the `.then` code to execute and I expected the responses coming ready to be processed.

However, what I am getting is a sort of sum up of the request:

```
Body: {"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"graph.facebook.com","port":443,"hostname":"graph.facebook.com","hash":null,"search":null,"query":null,"pathname":"/<WHATEVER>","path":"/<WHATEVER>","href":"https://graph.facebook.com/<WHATEVER>"},"method":"POST","headers":{"content-type":"multipart/form-data; boundary=73944c2c-f9d0-4489-9b65-85c68fc03bb0","content-length":650}}
```

I am testing the failure of one of the promises introducing a faulty one:

```
var faultyPromise = new Promise((resolve, reject) => setTimeout(() => reject(1), 3000));
pagesRequestPromiseArray.push(faultyPromise);
```

Stuff I tried already:

```
resolveWithFullResponse: true,
```

Hoping it would resolve with full response in my scenario, no luck.

A transformer function, didn't work either:

```
transform: function(response, body, anotherParam) {
	    	return response;
	    },
```

Is there a way of doing this I am missing?

Thanks in advance for your time! :+1:

**Comment by analog-nico** [comment]
Mmh, doesn’t this approach of using `Promis.all` have the issue that once one request fails, the catch handler will get executed immediately and some of the parallel running requests may not even be finished at this point? Considering this, I think the better approach would be to wrap each request individually and then call `Promise.all` on the wrapped requests.

**Comment by analog-nico** [comment]
Feel free to reopen @fcarriedos if you still need a solution.
