### ISSUE TITLE
 RequestError: Error: options.uri is a required argument

### ISSUE THREAD

**Issue by venkas01** [request/request-promise#302]
getting error : UnhandledPromiseRejectionWarning: RequestError: Error: options.uri is a required argument

code  : 
    var options = {
      method: "POST",
      headers: {
        Authorization:
          "Basic MjZmNTk4NWMtNW"
      },
      uri: "https://api.hana.ondemand.com/oauth2/apitoken/v1?grant_type=client_credentials",
    };

    let gettoken = await rp(options);
    console.log(gettoken);

**Comment by venkas01** [comment]
const getToken = async () => {

  try {
    var options = {
      method: "POST",
      headers: {
        Authorization:
          "Basic MjZmNTk4N
      },
      uri: "https://api.hana.ondemand.com/oauth2/apitoken/v1?grant_type=client_credentials",
    };

   let gettoken = await rp(options);
    console.log(gettoken);
    return gettoken;
  } catch (e) {
    console.log(e);
  }
};

**Comment by venkas01** [comment]
Can some one please help this is blocking by script.

i tried the same call with postman and it works.

**Comment by KayHS** [comment]
@venkas01 how did you solve this problem?

**Comment by kenshinji** [comment]
@venkas01 co-ask

**Comment by developer-sandip** [comment]
I am also having the same problem.How did you solve it ?
