### ISSUE TITLE
Upload stream and get response body

### ISSUE THREAD

**Issue by murat-mehmet** [request/request-promise#304]
I'm having problem with uploading a stream and reading response body. I tried many combinations for couple of days but nothing worked as expected. This is my function:
```
    postFile(url: string, filePath: string): Promise<any> {
        return new Promise((resolve, reject) => {
            const post = request.post({
                url: url,
                headers: this._headers,
                jar: this._jar,
                simple: false,
            });
            post.on('response', function(response){
                console.log(response.body);
                resolve(response.body);
            });
            fs.createReadStream(filePath).pipe(post); 
        });
    }
```

The problem here is that response.body returns empty. The shocking part was that when I try to listen it with fiddler and add `proxy: 'http://127.0.0.1:8888'` to the options, then the response body returns as expected, I have no idea why it does... Hope you can help me because I searched both request and request-promise issues and found nothing. All I need is uploading a file as stream and get response body.

Edit: At first I tried this, which should also work:
```
    postFile(url: string, filePath: any): Promise<any> {
        return request.post({
            url: url,
            headers: this._headers,
            jar: this._jar,
            simple: false,
            body: fs.createReadStream(filePath),
        });
    }
```
But it doesn't, simply returns empty body. Only thing that worked was `body: fs.readFileSync(filePath)` which reads the file as a buffer, not suitable for my case. I need to upload large files like ~50MB.

**Comment by analog-nico** [comment]
The second code snippet in [this example](https://github.com/request/request-promise#post-like-html-forms-do) uploads a file using a stream. Does this help?

**Comment by murat-mehmet** [comment]
That example uploads using multipart upload. The host I am uploading requires whole body as a file stream with Content-Type: image/jpeg, thus I have to pass stream as a body object. I don't understand why passing buffer to body works but stream does not. I'm totally stuck at this point.

**Comment by murat-mehmet** [comment]
Seems like a request issue. Closing this...
https://github.com/request/request/issues/3108

**Comment by analog-nico** [comment]
Indeed, `request` itself would need to add support for that. But since you need to pass the full image in the body, it means that you have to have the image fully in your memory. So a stream doesn’t really add any benefits. Instead, you could just use `fs.readFile(...)` and take care of the encoding.

**Comment by murat-mehmet** [comment]
Well for uploading image, I could use that, but in another request I need to upload a video... I hope they can provide me a workaround.
