### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by dariuszwrzesien** [request/request-promise#308]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for request-promise-core@1.1.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'request-promise'
npm ERR! notarget

**Comment by analog-nico** [comment]
Do you still have the problem? [`request-promise-core@1.1.2`](https://www.npmjs.com/package/request-promise-core) does exist on npm. Do you use another npm server that may not have loaded the latest available package versions yet?

**Comment by dariuszwrzesien** [comment]
It works without any changes. I use Nexus to manage npm package - and maybe there was a delay.
Thank you.

**Comment by analog-nico** [comment]
Alright, perfect!
