### ISSUE TITLE
Use Case: Wrap `pipe` events in promises

### ISSUE THREAD

**Issue by pulkitsinghal** [request/request-promise#32]
Thank you for putting this awesome abstraction together!

I came across a use case recently where I wanted to `.pipe` an arbitrary number of `request` results to my file system and `.then` finish my grunt task.

I would have loved to accomplish this via an abstraction of your library, I was wondering if you would consider looking at this use case and adding it out-of-the-box to your lib by wrapping `pipe` events in promises?

I accomplished it like so:

```
    var done = this.async();
    ...
          var downloaded = []; // make sure all the download pipes finish - step # 1
          var _ = require('underscore');
          var fs = require('fs');
          // GET for each resource
          _.each(paths, function(path){
            var filename = './downloded' + path + '.json';
            console.log(filename);
            var r = request
              .get(path)
              .on('error', function(err) {
                console.log(err);
                done();
              })
              // save in a file
              .pipe(fs.createWriteStream(filename));

            // make sure all the download pipes finish  - step # 2
            downloaded.push(
              new Promise(function (resolve, reject) {
                r.on('finish', function () {
                  console.log('pipe finished');
                  return resolve();
                });
              })
            );
          });

          // make sure all the download pipes finish - step # 3
          Promise.all(downloaded).then(function() {
            console.log('all the files were downloaded');
            done();
          });
```

**Comment by Xixiao007** [comment]
I am curious about the difference of two snippets below.
Actually I used the 2nd snippets, within which the `downloaded` does not wait until the file is downloaded completely. Then I switched to 1st, it works as expected.
Would you be kind to shortly explain ? @analog-nico

```
    var req = rp.get(path);
    req.on('error', function (err) { ... })
        .pipe(...);
    downloaded.push(req);
```
v.s.
```
    var req = rp.get(path).on('error', function (err) { ... })
        .pipe(...);
    downloaded.push(req);
```

**Comment by aledalgrande** [comment]
@xixiaofinland I don't know if you found out, but it's because the first snippet has a different `req`. In the first case you get a promise, in the second you get a stream.

**Comment by xixiaofinland** [comment]
> @xixiaofinland I don't know if you found out, but it's because the first snippet has a different `req`. In the first case you get a _promise_ from `.get`, in the second you get a _stream_ from `.pipe`.

You are right, thanks a lot!
