### ISSUE TITLE
Request is Deprecated!

### ISSUE THREAD

**Issue by mendel-payrix** [request/request-promise#340]
From the request docs

> As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. In fact, none have landed for some time.

See https://github.com/request/request/issues/3142

It would be helpful if this was mentioned in the docs here.

**Comment by mmcguff** [comment]
Please respond to whether there will be any attempt to migration request dependency to something else that isn't deprecated.  I have used this library extensively in a project and will be forced to migrate to use something else or fork this project and change it myself.  If this is already planned or especially if it wont be done, this will be helpful in determining how I and suppose many others in my same position.

**Comment by analog-nico** [comment]
I am sorry. A migration does not make sense as `request-promise` is just a wrapper around `request`. Replacing `request` would require another library that is a drop-in replacement for `request`. However, such a replacement does not exist and hence any solution would require migration efforts on the side of `request-promise` users. Since you would need to migrate anyway, you are better off migrating to another request library that already supports promises.

Please refer to the list of [alternative libraries to request](https://github.com/request/request/issues/3143).

**Comment by mjacksonest** [comment]
There is a deprecation warning on npm for request:
https://www.npmjs.com/package/request

The same deprecation warning does not currently exist for request-promise:
https://www.npmjs.com/package/request-promise

I suggest officially deprecating request-promise:
https://docs.npmjs.com/cli/deprecate

**Comment by JayeshThamke** [comment]
True! It is good suggestion from @mjacksonest to deprecate `request-promise` as `npm show` for `request-promise` does not show DEPRECATED warning. 

```
$ npm show request-promise

request-promise@4.2.5 | ISC | deps: 4 | versions: 41
The simplified HTTP request client 'request' with Promise support. Powered by Bluebird.
https://github.com/request/request-promise#readme

keywords: xhr, http, https, promise, request, then, thenable, bluebird

dist
.tarball: https://registry.npmjs.org/request-promise/-/request-promise-4.2.5.tgz
.shasum: 186222c59ae512f3497dfe4d75a9c8461bd0053c
.integrity: sha512-ZgnepCykFdmpq86fKGwqntyTiUrHycALuGggpyCZwMvGaZWgxW6yagT0FHkgo5LzYvOaCNvxYwWYIjevSH1EDg==
.unpackedSize: 36.8 kB

dependencies:
bluebird: ^3.5.0            request-promise-core: 1.1.3 stealthy-require: ^1.1.1    tough-cookie: ^2.3.3        

maintainers:
- analog-nico <nicolai.kamenzky@testrails.org>
- mikeal <mikeal.rogers@gmail.com>
- nylen <jnylen@gmail.com>
- request <request@outofindex.com>
- simov <simeonvelichkov@gmail.com>
- tyabonil <ty.abonil@gmail.com>

dist-tags:
0.1.1: 0.1.1   latest: 4.2.5  v0.1.0: 0.1.0  

published 8 months ago by analog-nico <nicolai.kamenzky@testrails.org>
```

It leads to PASS our sanity check scripts without detection of deprecated packages.

**Comment by analog-nico** [comment]
Thanks @mjacksonest and @JayeshThamke ! I added the deprecation warning.

**Comment by mjacksonest** [comment]
I see the warning and also noticed that it excludes request-promise from search results on npmjs.com.  Thanks!
