### ISSUE TITLE
How to see the request of a failed request ?

### ISSUE THREAD

**Issue by kopax** [request/request-promise#362]
I am doing a post request, when it fail, I can not see the headers sent, is there a way to see what where the headers sent?

Thanks for reading.

**Comment by analog-nico** [comment]
You can achieve this by using the `resolveWithFullResponse` parameter. Here is a [code example](https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body).

**Comment by kopax** [comment]
Thanks ! But does the full response appear in the `error` ? Anyway, I solved my issue.

**Comment by analog-nico** [comment]
Yes, the returned errors always contain `err.response` that includes the headers. Don’t mind the `resolveWithFullResponse` then. You don’t need it just for the error case.
