### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by chovy** [request/request-promise#44]
Is there a way to set the timeout for the request?

**Comment by analog-nico** [comment]
Hi @chovy , yes there is. Please have a look at the [Request documentation](https://github.com/request/request#requestoptions-callback). You can use the `timeout` option.

**Comment by analog-nico** [comment]
Hi @chovy did my answer help? Can I give you some more info? If you are fine I would close this issue.

**Comment by chovy** [comment]
Yes. Thank you.
