### ISSUE TITLE
Same contributing rules as for request?

### ISSUE THREAD

**Issue by analog-nico** [request/request-promise#46]
@tyabonil Request uses a nice [CONTRIBUTING.md](https://github.com/request/request/blob/master/CONTRIBUTING.md) which we could add to Request-Promise as well.

+1 ?

**Comment by tyabonil** [comment]
I'm not really opposed, but it's only 4 people in the repo, with you doing most of the work:)  Happy either way.

**Comment by analog-nico** [comment]
:D Good point, actually. Maybe we shouldn't overcomplicate a project for a 200 LOC library at least for now. ;)
