### ISSUE TITLE
error when importing request-promise

### ISSUE THREAD

**Issue by barbalex** [request/request-promise#51]
I have installed request-promise via npm

    npm i --save request-promise

Then I import it into a file:

    import rq from 'request-promise'

Now I get this message:

    ERROR in ./~/request-promise/~/request/lib/har.js
    Module not found: Error: Cannot resolve module 'fs' in C:\Users\alex\ae\node_modules\request-promise\node_modules\reques
    t\lib
     @ ./~/request-promise/~/request/lib/har.js 3:9-22

    ERROR in ./~/request-promise/~/request/~/forever-agent/index.js
    Module not found: Error: Cannot resolve module 'net' in C:\Users\alex\ae\node_modules\request-promise\node_modules\reque
    st\node_modules\forever-agent
     @ ./~/request-promise/~/request/~/forever-agent/index.js 6:10-24

    ERROR in ./~/request-promise/~/request/~/forever-agent/index.js
    Module not found: Error: Cannot resolve module 'tls' in C:\Users\alex\ae\node_modules\request-promise\node_modules\reque
    st\node_modules\forever-agent
     @ ./~/request-promise/~/request/~/forever-agent/index.js 7:10-24

    ERROR in ./~/request-promise/~/request/~/tough-cookie/lib/cookie.js
    Module not found: Error: Cannot resolve module 'net' in C:\Users\alex\ae\node_modules\request-promise\node_modules\reque
    st\node_modules\tough-cookie\lib
     @ ./~/request-promise/~/request/~/tough-cookie/lib/cookie.js 32:10-24

    ERROR in ./~/request-promise/~/request/~/tunnel-agent/index.js
    Module not found: Error: Cannot resolve module 'net' in C:\Users\alex\ae\node_modules\request-promise\node_modules\reque
    st\node_modules\tunnel-agent
     @ ./~/request-promise/~/request/~/tunnel-agent/index.js 3:10-24

    ERROR in ./~/request-promise/~/request/~/tunnel-agent/index.js
    Module not found: Error: Cannot resolve module 'tls' in C:\Users\alex\ae\node_modules\request-promise\node_modules\reque
    st\node_modules\tunnel-agent
     @ ./~/request-promise/~/request/~/tunnel-agent/index.js 4:10-24

    ERROR in ./~/request-promise/~/request/~/har-validator/~/is-my-json-valid/~/jsonpointer/jsonpointer.js
    Module not found: Error: Cannot resolve module 'console' in C:\Users\alex\ae\node_modules\request-promise\node_modules\r
    equest\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\jsonpointer
     @ ./~/request-promise/~/request/~/har-validator/~/is-my-json-valid/~/jsonpointer/jsonpointer.js 1:14-32

This is my package.json, just in case:

    {
      "name": "ae",
      "version": "1.0.0",
      "description": "arteigenschaften.ch",
      "main": "index.js",
      "scripts": {
        "start": "webpack-dev-server",
        "prebuild": "gulp cleanPublic",
        "build": "set NODE_ENV=production&& webpack",
        "test": "standard"
      },
      "author": "Alexander Gabriel",
      "license": "ISC",
      "dependencies": {
        "ampersand-app": "1.0.4",
        "ampersand-router": "3.0.2",
        "autolinker": "0.18.1",
        "autoprefixer-core": "5.2.1",
        "babel": "5.6.23",
        "babel-loader": "5.3.2",
        "bootstrap": "3.3.5",
        "classnames": "2.1.3",
        "css-loader": "0.15.5",
        "del": "1.2.0",
        "file-loader": "0.8.4",
        "gulp": "3.9.0",
        "hjs-webpack": "2.10.0",
        "jquery": "2.1.4",
        "json-loader": "0.5.2",
        "local-links": "1.4.0",
        "lodash": "3.10.0",
        "node-libs-browser": "0.5.2",
        "postcss-loader": "0.5.1",
        "pouchdb": "3.6.0",
        "pouchdb-all-dbs": "^1.0.1",
        "pouchdb-load": "^1.4.0",
        "react": "0.13.3",
        "react-bootstrap": "0.23.7",
        "react-favicon": "0.0.3",
        "react-hot-loader": "1.2.8",
        "react-json-inspector": "5.1.0",
        "react-textarea-autosize": "2.4.0",
        "react-typeahead": "^1.1.1",
        "reflux": "0.2.10",
        "request-promise": "^0.4.2",
        "require-dir": "0.3.0",
        "style-loader": "0.12.3",
        "stylus-loader": "1.2.1",
        "surge": "0.14.3",
        "url-loader": "0.5.6",
        "webpack": "1.10.1",
        "webpack-dev-server": "1.10.1",
        "yeticss": "7.0.1"
      },
      "standard": {
        "ignore": [
          "public/*"
        ]
      }
    }

**Comment by barbalex** [comment]
I just realized that this seems to be a request issue rather than a request-promise issue. Moved the issue to request (https://github.com/request/request/issues/1691)

**Comment by CallMeTommy1988** [comment]
hi. now about this question?

i want to use

```
import rq from 'request-promise'
```

but error
