### ISSUE TITLE
export `RequestError` and `StatusCodeError`

### ISSUE THREAD

**Issue by derhuerst** [request/request-promise#52]
Since I want to reliably detect what type of error occured, I need to check `err` in the error handler using `err instanceof …`. This is only possible if request-promise `export`s the constructors. Please do so.

**Comment by analog-nico** [comment]
Yes, see [at the end of this section](https://github.com/request/request-promise#rejected-promises-and-the-simple-option). Is that all you need?

**Comment by derhuerst** [comment]
Thanks, didn't see that.
