### ISSUE TITLE
Make a POST request with data on request body

### ISSUE THREAD

**Issue by lucasfeliciano** [request/request-promise#56]
I looked into the documentation and didnt find anything about it.

I'm wondering if I can make a POST passing the parameters into the body instead as a query string.

Is that possible?

**Comment by analog-nico** [comment]
Hi @lucasfeliciano I recently discussed this question on [Gitter](https://gitter.im/request/request-promise) as well. This was the solution:
``` js
var rp = require('request-promise');
rp({
    uri: apiEndpoint,
    method: 'POST',
    json: true,
    body: jsonData
});
```
BTW, Request-Promise is just adding the Promise capability to Request. In [Request's README](https://github.com/request/request) you find its usage explained which is also valid for Request-Promise.

Did this answer your question?

**Comment by lucasfeliciano** [comment]
Thank you @analog-nico. :)

**Comment by mLuby** [comment]
In case anyone else is looking for the syntactic sugar for this (which is poorly documented) it's 
```js
request.post("http://test.com", {json: {foo: "bar"}) // JSON request has body {"foo": "bar"}
```
