### ISSUE TITLE
How to handle cookies?

### ISSUE THREAD

**Issue by brunano21** [request/request-promise#57]
Hi! 
Before of using this lib, I was using the non-promise version of request, where I was able to send into a GET also some cookies, as the follow:

    var j = req.jar();
    var url = "my_url";
    var cookie = req.cookie("" + mycookie);
    j.setCookie(cookie, url);
    req({ uri: url, method: "GET", jar: j }, function(....));

By now with the same options, but using promise-request, I'm getting an error into catch function, saying just this:
`[SyntaxError: Unexpected token u]`

Am I missing something?
Thanks in advance!

**Comment by analog-nico** [comment]
Hi @brunano21 !
Since Request-Promise exports the original Request object instead of wrapping it, the interface is completely identical. That means you don't miss anything.

Since Request-Promise still supports using a callback you may try this: First write the code with `require('request')`:

``` js
var req = require('request'); // or require('request-promise/node_modules/request')

var j = req.jar();
var url = "my_url";
var cookie = req.cookie("" + mycookie);
j.setCookie(cookie, url);
req({ uri: url, method: "GET", jar: j }, function(....));
```

After you verified that the code above is working require Request-Promise:

``` js
var req = require('request-promise'); // just this line is changed

var j = req.jar();
var url = "my_url";
var cookie = req.cookie("" + mycookie);
j.setCookie(cookie, url);
req({ uri: url, method: "GET", jar: j }, function(....));
```

If it is still not working please let me know and I'll test it out myself.

**Comment by brunano21** [comment]
I just verified that the error is into the `then` function, where basically I parse a JSON obj (which contains a ú (U with accent)) through `JSON.parse(response.body)`.

So then the question is: why do not I get this error with the non-promise request?
By the way, my new request options are: 
`{ uri: url, method: "GET", jar: cookieJar, headers: {'Content-Type': 'application/json;charset=utf-8'}}`

Thanks!

**Comment by brunano21** [comment]
Sorry! Never mind, I messed a bit with my code and I realised that I was trying to parse `response.body` which is undefined since the body is the response. I'm so sorry!

**Comment by analog-nico** [comment]
No problem. Happy coding!

**Comment by chovy** [comment]
can you put a mention of this in README.md -- I always end up here.

**Comment by kristofkotai** [comment]
this is such an inconvenient interface for setting cookies...

**Comment by analog-nico** [comment]
FYI, there is a good [cookie usage example](https://github.com/request/request-promise#include-a-cookie) in the README now.

**Comment by maddy2894** [comment]
Hi @analog-nico, I am sending requests with cookies between my two domains. Is there any way to access the cookie in second domain? 
Like, sending `body: {key: value}`, it can be accessed on other end using `req.body`, any such way to access cookie?
