### ISSUE TITLE
Can this be used in client side ?

### ISSUE THREAD

**Issue by alexserver** [request/request-promise#60]
Is there any way for this package to be used in client side ?
I'm looking for a non-jquery node module to be used in client-side, and pack it via webpack.
This module seemed to be good but the requirement of fs doesn't let webpack to work with it.

Is there any workaround for this ? or any way to just load enough scripts for client side to pack ?

**Comment by analog-nico** [comment]
Hi @alexserver, I am sorry Request-Promise was designed to be used in a node.js environment only. You may try [SuperAgent](https://visionmedia.github.io/superagent/) instead.
