### ISSUE TITLE
Stub out module request-promise by using sinon, but it still sends out real request with unexpected return parameters

### ISSUE THREAD

**Issue by wangpin34** [request/request-promise#61]
[request-promise](https://github.com/request/request-promise) is cool but seems not easy to work with [sinon](https://github.com/cjohansen/Sinon.JS). I use [proxyquire](https://github.com/thlorenz/proxyquire) to replace depend rquest-promise in my module with stubed request. But seems it doesn't work as expected because a real request is sending out. Then I use original [request](https://github.com/request/request) lib for my module, and stud it. And this time it works as expected.  How strange!  

Is this a real problem that need to be fixed?

**Comment by analog-nico** [comment]
Hi @wangpin34 mocking is indeed an unresolved issue. For alternatives to sinon.js please have a look at issue #55.

I might be able to guess why proxyquire works for Request but not for Request-Promise. To see whether we can fix that could you give me some code snippets? One where you successfully proxyquire'd Request and one where you tried the same for Request-Promise please. Thank you!

**Comment by wangpin34** [comment]
@analog-nico  I have made mistakes in my unit-test for company business code, I guess. It's a bit of complicated. So I created tiny code snippets for testing this and then I found the issue is not like what I have side previously.

app.js:
```
var request = require('request-promise');

module.exports = {
	searchMe: function(url) {
		return request(url);
	}
};

```

test-app.js:
```
var sinon = require('sinon'),
	proxyquire = require('proxyquire');

describe('Test app function', function() {
	var app,
		request,
		url = 'http://github.com/wangpin34',
		body = JSON.stringify({
			location: 'shanghai'
		});

	before(function() {
		request = sinon.stub();
		app = proxyquire('../lib/app', {
			'request-promise': request
		});
	});

	it('searchme should report me is in shanghai ', function(done) {

		request.withArgs(url).yields(body);

		app.searchMe(url).then(function(data){
			console.log(data);
			done();
		});
	});
});
```

For above code, I got error when run mocha test:

 TypeError: stub expected to yield, but no callback was passed. Received [ht
/github.com/wangpin34]

And test failed.

It seems like problem was caused by sinonjs.  And this issue could be closed. Thanks.

PS. Tomorrow I will go into my working code to see why the issue happened in previous post. If I got something, will share it here.

**Comment by analog-nico** [comment]
Thanks @wangpin34. If you replace Request-Promise itself it should always work. I was previously referring to an internal binding between Request-Promise and Request. Anyway, I will extend the README to cover best practices for mocking the lib when I have time.

**Comment by wangpin34** [comment]
Thanks you,@analog-nico, and your great work.

**Comment by neoadventist** [comment]
@wangpin34 did you ever get this to work? Thanks!

**Comment by kaiyuanneo** [comment]
This also wasn't working for me but I found a workaround with Nock: https://github.com/request/request-promise/issues/55#issuecomment-373903096
