### ISSUE TITLE
How to handle an error in the body 

### ISSUE THREAD

**Issue by MichielDeMey** [request/request-promise#63]
Hey guys

I have this peculiar requirement to check the body for an error object, since the API that I'm working with will return a status code of 200 along with an error object in the body.

```HTTP
200 OK
{
  "error": "shitty API's error response"
}
```

Is there an easy way to define what should trigger an error, preferably using the `defaults` setting so that I can keep the codebase clean and DRY.

I've read up on the `simple` options, however I'm not sure of it's the right way to go.

In addition, I was hoping to use the `transform` function to reject the promise however the promise itself is not accessible from within the function?

Unless it's accessible in the `transform` using something like

```js
this.promise().reject();
```

Thanks

**Comment by analog-nico** [comment]
Hi @MichielDeMey the `transform` function is actually your best friend. As you see in the tests you may either [return a rejected promise](https://github.com/request/request-promise/blob/master/test/spec/request-test.js#L326-L341) or [throw an `Error`](https://github.com/request/request-promise/blob/master/test/spec/request-test.js#L343-L360) inside the `transform` function.

You can also [pass the `transform` function to `.defaults(...)`](https://github.com/request/request-promise/blob/master/test/spec/request-test.js#L470-L479) which then hopefully meets your DRY goal.

Let me know if this solves what you need.

**Comment by MichielDeMey** [comment]
Hey @analog-nico 

This is exactly what I needed!

One minor downside is that we have to create a new Promise and reject that one instead of having a reference to the promise itself which we can reject. But I can live with that small overhead.

Now I just have to figure out the following error thrown by Request:
(This error is thrown both by using the rejected promise and throwing a new error)

```
Possibly unhandled Error: [error message here]
```

Which is discussed here: https://github.com/petkaantonov/bluebird#error-handling

**Comment by analog-nico** [comment]
Great!

You may just throw the Error inside the transform function and you won't have the overhead of creating another promise.

The "Possibly unhandled Error" is printed if you don't call `.catch(...)` or call it too late.

**Comment by MichielDeMey** [comment]
I've decided to just throw the Error in order to avoid the overhead of creating a new Promise.

Thanks!

**Comment by analog-nico** [comment]
You are welcome!
