### ISSUE TITLE
Error: "name" and "value" are required for setHeader()

### ISSUE THREAD

**Issue by sergiovilar** [request/request-promise#68]
When I try to made any request passing the options object I receive this error, even if I didn't pass the `headers` property :(

Could anyone help me here?

Thanks!

**Comment by analog-nico** [comment]
Did you find the solution or did you close the issue by accident?

**Comment by sergiovilar** [comment]
I opened the issue by accident, sorry!

**Comment by analog-nico** [comment]
No problem. Happy coding!
