### ISSUE TITLE
[Question] Get result for new request

### ISSUE THREAD

**Issue by Vietworm** [request/request-promise#69]
I need results from request promise then() after, and use again result for new request ?? How do that?
I hope, have someone support my question. Thanks !

```javascript
   let opt = {
        method: 'POST',
        uri: API,
        body: {
            news_id: id
        },
        json: true
    };

    rp(opt).then(function (result) {
        rpt(opt2).then(function () { // error
        })
    })
```

**Comment by analog-nico** [comment]
Hi @Vietworm , your code looks good already. I would further improve the way you use the promises:

``` js
rp(opt)
    .then(function (result) {
        let opt2 = { /* with data from result */ };
        return rp(opt2); // The `return` inserts the second request into the promise chain.
    })
    .then(function (resultOfSecondRequest) {
        // Process resultOfSecondRequest here...
    })
    .catch(function (err) {
        // Handle any error from the first, the second request, or the final processing here...
    });
```

Does this help?

**Comment by Vietworm** [comment]
@analog-nico thanks for answer :)

I've been tried it but throw error
```
Unhandled rejection RequestError: Error: Argument error, options.body.
```

**Comment by analog-nico** [comment]
Since it says `Argument error, options.body` you got something wrong with the `body` option. You find some details about this option [here](https://github.com/request/request#requestoptions-callback).

Since it is also saying `Unhandled rejection` means that you did not properly add a `.catch(...)` handler. My code above does this properly.

If you need both results then you may use:
``` js
rp(opt)
    .then(function (result) {
        let opt2 = { /* with data from result */ };
        return [result, rp(opt2)];
    })
    .spread(function (resultOfFirstRequest, resultOfSecondRequest) {
        // Process both results here...
    })
    .catch(function (err) {
        // Handle any error from the first, the second request, or the final processing here...
    });
```

**Comment by Vietworm** [comment]
Thanks so much @analog-nico.
My fault, i defined options not enough. As the forgotten `json: true` option.

**Comment by analog-nico** [comment]
You are welcome.
