### ISSUE TITLE
 Cannot set property 'noConflict' of undefined

### ISSUE THREAD

**Issue by reggi** [request/request-promise#72]
I have no clue what's going on here:

```
TypeError: /Users/thomas/Desktop/shopify-util/__tests__/shopify-util-test.js: /Users/thomas/Desktop/shopify-util/shopify-util.js: /Users/thomas/Desktop/shopify-util/node_modules/request-promise/lib/rp.js: /Users/thomas/Desktop/shopify-util/node_modules/request-promise/node_modules/bluebird/js/main/bluebird.js: Cannot set property 'noConflict' of undefined
```

**Comment by analog-nico** [comment]
This is related to Bluebird. Before you ask the Bluebird community you might paste your code snippet with your Request-Promise call here and I can check if it is somehow related to how you use Request-Promise.

**Comment by analog-nico** [comment]
Hi @reggi did you find a solution? Can I help?

**Comment by reggi** [comment]
Hey @analog-nico, I gave up on whatever it was I was doing. If I run into it again I'll be sure to post a more detailed issue. Thanks for the help. Ok to close.

**Comment by analog-nico** [comment]
Alright. See ya!
