### ISSUE TITLE
How to use with SOAP?

### ISSUE THREAD

**Issue by AlaRuba** [request/request-promise#73]
Hi,

I couldn't find any sample code on how to connect to SOAP with this.

**Comment by analog-nico** [comment]
Hi @AlaRuba 
Request-Promise only adds promise support to the [Request](https://github.com/request/request) library. Request is the library that does the actual work of doing the requests. So if you look for a solution you can google for Request examples and apply them to Request-Promise the same way. Request doesn't provide higher level functions to talk SOAP. However, sending XML requests is of course possible. See [this answer](http://stackoverflow.com/a/28639197/3477940) for a practical approach to use Request-Promise with SOAP.

Please let me know if that answers your question.

**Comment by AlaRuba** [comment]
Thanks so much. I ended up just doing a POST request with the XML

**Comment by analog-nico** [comment]
You are welcome.
