### ISSUE TITLE
No response headers in response object

### ISSUE THREAD

**Issue by ir-fuel** [request/request-promise#74]
Hi

This is what I do:

```
const options = {
    method:'GET',
    uri:BaseUrl+path,
    resolveWithFullResponse :true
  }


rp(options).then(function(response) {
    console.log(response.headers)
```

Result is `{}`

However when I look in the Chrome developer tools I see:
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Headers: X-Requested-With,Content-Type,authorization
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Impvc2tlIiwiZW1haWwiOiJqb3Jpc0Bhc3R1cy5iZSIsInBhc3N3b3JkSGFzaCI6IiQyYSQxMCQwN0JYOTdGMmR3YXd6VFdoLnEvUEZPWXJhYUVOMlN5NjlobkZEWUplRnExNTVtTTluUVByVyIsImlhdCI6MTQ0Njc1NTEwMywiZXhwIjoxNDQ2NzY1OTAzfQ.SdcXC69nkRxfIn1DbHx-F9_xzW-kC6kvwn26uaNkrJI
Date: Thu, 05 Nov 2015 20:25:03 GMT
Connection: keep-alive
Content-Length: 160
```

Where did all those headers go? 

I am calling this in client-side javascript (using webpack).

Thanks!

**Comment by analog-nico** [comment]
Hi @ir-fuel I tried it as well with this code:

``` js
var rp = require('request-promise');

rp({
    uri: 'http://google.com',
    method: 'GET',
    resolveWithFullResponse: true
})
    .then(function (response) {
        console.dir(response.headers);
    });
```

And on the console I get:

``` cmd
$ node issue74.js 
{ date: 'Mon, 09 Nov 2015 12:11:51 GMT',
  expires: '-1',
  'cache-control': 'private, max-age=0',
  'content-type': 'text/html; charset=ISO-8859-1',
  p3p: 'CP="This is not a P3P policy! See http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=151657 for more info."',
  server: 'gws',
  'x-xss-protection': '1; mode=block',
  'x-frame-options': 'SAMEORIGIN',
  'set-cookie': 
   [ 'PREF=ID=1111111111111111:FF=0:TM=1447071111:LM=1447071111:V=1:S=4ikNO-LjSbzyj9Ah; expires=Thu, 31-Dec-2015 16:02:17 GMT; path=/; domain=.google.de',
     'NID=73=idhblUcPmb_5uu2sc4TwQ9PYqZeRGC_cnjWJDXSBiLMlwrR18OnHHZ8RxHQwH-LqiiALkfWSOTP2xhLeDnya-pKIzDPUvOhT2emf1tH2yxvzc1n7LQAH9g6x58asR5-hFgHC1Oxx3RDtTv8yYgckmapILgPx2LBh; expires=Tue, 10-May-2016 12:11:52 GMT; path=/; domain=.google.de; HttpOnly' ],
  'accept-ranges': 'none',
  vary: 'Accept-Encoding',
  connection: 'close' }
```

Since it looks good can you check your code again? Maybe get the latest version of Request-Promise and Request?

**Comment by analog-nico** [comment]
Hi @ir-fuel , did you resolve this issue by yourself? Or can I help?

**Comment by ir-fuel** [comment]
Hi, it must be something else inside my project that 'eats' the headers. I tried it in a standalone project and there they work just fine.

**Comment by analog-nico** [comment]
I see. Just some pointers: If you google for answers you may just include "request" in your search. That you actually use Request-Promise doesn't matter in your case. Also, if you use something like browserify you may investigate whether this is maybe caused by their http shim instead of Request.

**Comment by Sereda-Fazen** [comment]
Hi All! Could you tell me it's possible to get token from header response ?
currently I get 
  `{ 'content-length': '1060',
  'content-type': 'text/html',
  'last-modified': 'Thu, 18 Oct 2018 10:56:55 GMT',
  'accept-ranges': 'bytes',
  etag: '"80b56e48d166d41:0"',
  server: 'Microsoft-IIS/10.0',
  'x-powered-by': 'ASP.NET',
  'set-cookie':
   [ 'ARRAffinity=5c2f0a04eaf665015468e80170287bd43d0d86b3b30972eb2bd7c60c3fdca4a8;Path=/;HttpOnly;Domain=kh-fcc-at.azurewebsites.net' ],
  date: 'Thu, 18 Oct 2018 12:07:42 GMT',
  connection: 'close' }`

But I want to get token in header:

`authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Impvc2tlIiwiZW1haWwiOiJqb3Jpc0Bhc3R1cy5iZSIsInBhc3N3b3JkSGFzaCI6IiQyYSQxMCQwN0JYOTdGMmR3YXd6VFdoLnEvUEZPWXJhYUVOMlN5NjlobkZEWUplRnExNTVtTTluUVByVyIsImlhdCI6MTQ0Njc1NTEwMywiZXhwIjoxNDQ2NzY1OTAzfQ.SdcXC69nkRxfIn1DbHx-F9_xzW-kC6kvwn26uaNkrJI`

**Comment by anthonysapien** [comment]
I just ran into the same problem and was able to figure it out from these links:
https://glaucocustodio.github.io/2016/01/20/dont-forget-to-expose-headers-when-using-rack-cors/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
https://github.com/cyu/rack-cors

You'll see the response header in the browser dev tools, but they won't arrive to the client unless you expose them from the server.

`resource '*',
      headers: :any,
      methods: %i(get post put patch delete options head),
      expose: ['Authorization']`
