### ISSUE TITLE
rp.defaults not working for transform

### ISSUE THREAD

**Issue by pke** [request/request-promise#77]
It seems the `transform` function is never called, as described in the docs.

```
rp.defaults({transform: function(body) {
  return cheerio.load(body);
});
```

It will just call into `request.defaults` and that does not know about `transform` and ignores it.

**Comment by analog-nico** [comment]
Hi @pke, there is a [test case](https://github.com/request/request-promise/blob/master/test/spec/request-test.js#L500-L509) that ensures that this works appropriately. Did you use the return value of `rp.defaults(...)` instead of `rp` to make your request?

**Comment by analog-nico** [comment]
Were you able to resolve this issue @pke or can I help?

**Comment by analog-nico** [comment]
Hi @pke I assume I can close this issue now. Let me know if you still have questions.
