### ISSUE TITLE
Fallback to throw incompatible with ES7

### ISSUE THREAD

**Issue by seriph** [request/request-promise#78]
Falling back to error throws when no listener is registered is preventing ES7 compatibility. 
I'm using Babel/ES7 awaits, which work with Promises. If you don't immediately await on the Promise returned by request-promise, and an error appears, the library throws an error. 
I had to solve this by calling .promise() to mark that the promise was in use. 

Would be nice if you could turn this off via an option, because it would prepare the library for ES7-style promise handling.

**Comment by analog-nico** [comment]
Hi @seriph judging from your explanation you are probably still using an old version of Request-Promise. Is that true? With version 1.0.0 Request-Promise always expects the user to use the promise and passes errors to the reject handler.

If you actually get a thrown error with the latest version of Request-Promise then please provide a code snippet so I can reproduce it. Thanks.

**Comment by analog-nico** [comment]
Anything you might want to add @seriph ?

**Comment by analog-nico** [comment]
Hi @seriph I assume there is no TODO here. Let me know if the problem is not solved.

**Comment by seriph** [comment]
You were correct, using an old version. Thanks for following up!

**Comment by analog-nico** [comment]
You are welcome!
