### ISSUE TITLE
please add cookie handling to readme

### ISSUE THREAD

**Issue by chovy** [request/request-promise#79]
i want to know how to create a cookie jar as well as parse the cookie jar manually.

edit: and also add custom cookie to the request object.

**Comment by analog-nico** [comment]
Hi @chovy the second half of [Request's examples section](https://github.com/request/request#examples) explains the use of the `jar` option quite well.

Did you open this issue to ask this for your own purposes or do you believe that this is very important and should be added to the Request-Promise README as well?

**Comment by chovy** [comment]
I would at least add a section pointing to the request docs in the request-promise readme.md

**Comment by analog-nico** [comment]
Hi @chovy we are currently [working on a brand new Request/Request-Promise documentation](https://github.com/request/request/issues/1987). I will make sure to include the cookie handling.

**Comment by chovy** [comment]
thanks.

**Comment by ProfessorTom** [comment]
+1

I would really like to see how to use cookies and cookie jars on the `request-promise` README.md

**Comment by analog-nico** [comment]
Hey everyone, I just added an [example](https://github.com/request/request-promise#include-a-cookie) to the README. Please make sure to use `request-promise@4.2.1` or higher for this to work. Version 4.2.1 includes a bug fix that made using `tough-cookie` possible.
