### ISSUE TITLE
Multiple requests in parallel

### ISSUE THREAD

**Issue by peacechen** [request/request-promise#81]
Does request-promise support loading multiple uri's in parallel?  Loading in series is possible using chained .thens (albeit not pretty), but I don't see a way to load them in parallel.

**Comment by analog-nico** [comment]
Yes. But this is something promises themselves do. If you use Bluebird you may use this code:

``` js
var Bluebird = require('bluebird');
var rp = require('request-promise');

var request1 = rp(paramsReq1);
var request2 = rp(paramsReq2);
var request3 = rp(paramsReq3);

Bluebird.all([request1, request2, request3])
    .spread(function (responseOfReq1, responseOfReq2, responseOfReq3) {
        // All requests succeeded.
        // Process the responses now.
    })
    .catch(function (err) {
        // At least one request failed.
        // Do your error handling here.
    });
```

Does this help?

**Comment by peacechen** [comment]
I didn't realize request-promise could be mixed with Bluebird like that.  Makes sense since you use it within request-promise.  Would it be possible to pass it to another promise library such as Q?

Thank you for the sample code!

**Comment by analog-nico** [comment]
Yes, you may use Q as well.

**Comment by analog-nico** [comment]
Hi @peacechen , fyi, I just released [`request-promise-any`](https://github.com/request/request-promise-any) which is equivalent to `request-promise` and allows you to register Q to be used even internally. If you are using Q in your project then you wouldn't have to worry about mixing Bluebird and Q anymore.
