### ISSUE TITLE
continuation-local-storage errors

### ISSUE THREAD

**Issue by rstacruz** [request/request-promise#82]
Using request-promise, I get these npm warnings:

> npm ERR! peer invalid: continuation-local-storage@~3, required by cls-bluebird@1.0.1

This warning is preventing me from doing `npm shrinkwrap`. What is continuation-local-storage and why is it necessary for request-promise to work? and if it's a peerDependency of one of request-promise's dependencies, why isn't it a dependency here?

**Comment by analog-nico** [comment]
Hi @rstacruz see pull request #75 . I will take care of that in a few days.

**Comment by analog-nico** [comment]
Thanks @rstacruz for reminding me of that issue. It was known far too long and about time to fix it! I just released `request-promise@2.0.0` which fixes that.

**Comment by analog-nico** [comment]
Hi @rstacruz , I just released `request-promise@4.0.0` which dropped the `continuation-local-storage` and `cls-bluebird` altogether. Maybe you can remove any workarounds now which you still have in place.

**Comment by rstacruz** [comment]
Neat!
