### ISSUE TITLE
How to abort a pending request?

### ISSUE THREAD

**Issue by ismriv** [request/request-promise#85]
The library [request](https://github.com/request/request/) has a function `abort` (see https://github.com/request/request/issues/772) that can be called for this purpose. However, `request-promise` returns a Promise, and therefore it has no such function. How does one abort/cancel a request then?

**Comment by analog-nico** [comment]
Hi @ismriv! Actually, Request-Promise returns the same object as Request which was just extended by promise functionality. Thus `.abort()` still exists and can be used.

``` js
var rp = require('request-promise');

var r = rp('http://google.com');

r.then(function (body) {
        console.dir(body);
    })
    .catch(function (err) {
        console.dir(err);
    });

r.abort();
```

If you call `.abort()` the promise will neither be resolved nor rejected though.

**Comment by ismriv** [comment]
Thanks @analog-nico. The problem was that I was calling `.promise()` and the underlying promise doesn't have access to the original request's `abort` function.

**Comment by analog-nico** [comment]
Ah, yes. 👍
